import * as React from 'react';
import { createContext, useState, useContext, ReactNode, useEffect } from 'react';

// 1. Хэлний төрлүүдээ энд тодорхойлно (Бүх шинэ хэлийг нэмэв)
export type Language = 'mn' | 'en' | 'cn' | 'ru' | 'ja' | 'ko' | 'de' | 'fr' | 'es' | 'it';

// 2. Хэл сонгох цэсэнд харагдах өгөгдөл (Далбаа, уугуул нэр)
export interface LanguageOption {
    code: Language;
    name: string;
    nativeName: string;
    flag: string;
}

export const supportedLanguages: LanguageOption[] = [
    { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', flag: '🇲🇳' },
    { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
    { code: 'cn', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
    { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
    { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
    { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
    { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
    { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
    { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
    { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// 3. Орчуулгын том объект (Таны хуучин орчуулгууд + Шинэ хэлнүүд)
// Жич: Таны хуучин 'mn', 'en', 'cn' орчуулгууд ЯГ ХЭВЭЭРЭЭ байгаа.
const translations: Record<Language, Record<string, string>> = {
  mn: {
    welcome_back: 'Тавтай морилно уу',
    login_subtitle: 'Үргэлжлүүлэхийн тулд нэвтрэнэ үү',
    email: 'Имэйл',
    password: 'Нууц үг',
    login: 'Нэвтрэх',
    logging_in: 'Нэвтэрч байна...',
    forgot_password: 'Нууц үг мартсан?',
    reset_password: 'Нууц үг сэргээх',
    send_recovery_link: 'Код илгээх',
    enter_recovery_code: 'Сэргээх код',
    new_password: 'Шинэ нууц үг',
    update_password: 'Нууц үг солих',
    code_sent: 'Таны имэйл рүү код илгээлээ (Жишээ: 123456)',
    phone_verification: 'Утас баталгаажуулалт',
    verify_now: 'Баталгаажуулах',
    verified: 'Баталгаажсан',
    unverified: 'Баталгаажаагүй',
    send_code: 'Код илгээх',
    enter_code: 'Код оруулах',
    verify: 'Шалгах',
    phone_code_sent: 'Таны утас руу код илгээлээ (Жишээ: 5555)',
    invalid_code: 'Код буруу байна',
    success_verified: 'Амжилттай баталгаажлаа!',
    registration_success: 'Амжилттай бүртгэгдлээ!',
    recovery_instruction: 'Имэйл хаягаа оруулна уу, бид таны нууц үг сэргээх код имэйлээр илгээх болно.',
    sending: 'Илгээж байна...',
    recovery_code_instruction: 'Имэйлээр илгээсэн 6 оронтой код болон шинэ нууц үгээ оруулна уу.',
    updating: 'Шинэчлэж байна...',
    no_account: 'Бүртгэлгүй юу?',
    sign_up: 'Бүртгүүлэх',
    create_account: 'Бүртгэл үүсгэх',
    choose_role: 'Төрлөө сонгоно уу',
    how_will_use: 'Та платформыг хэрхэн ашиглах вэ?',
    traveler: 'Аялагч',
    traveler_desc: 'Аялал төлөвлөх & газар үзэх.',
    guide: 'Хөтөч',
    guide_desc: 'Аялал удирдах & туршлага хуваалцах.',
    provider: 'Байгууллага',
    provider_desc: 'Камп & үйлчилгээ удирдах.',
    already_account: 'Бүртгэлтэй юу?',
    full_name: 'Бүтэн нэр',
    phone: 'Утас',
    creating_account: 'Үүсгэж байна...',
    feed: 'Нүүр',
    guides: 'Хөтөч',
    providers: 'Үйлчилгээ',
    profile: 'Профайл',
    search_placeholder: 'Хөтөч, үйлчилгээ, пост хайх...',
    no_results: 'Илэрц олдсонгүй.',
    no_posts: 'Пост алга. Та анхныхыг оруулаарай!',
    create_post: 'Пост оруулах',
    share_experience: 'Аялалын туршлагаа хуваалцаарай...',
    post: 'Нийтлэх',
    posting: 'Нийтлэж байна...',
    cancel: 'Болих',
    photo_video: 'Зураг/Бичлэг',
    promote_service: 'Үйлчилгээ сурталчлах',
    info: 'Мэдээлэл',
    my_bookings: 'Миний захиалгууд',
    edit: 'Засах',
    save_changes: 'Хадгалах',
    location: 'Байршил',
    experience: 'Туршлага',
    visited_places: 'Очсон газрууд',
    service_desc: 'Үйлчилгээний тайлбар',
    public: 'Нээлттэй?',
    logout: 'Гарах',
    verification: 'Баталгаажуулалт',
    verification_method: 'Баталгаажуулалтын арга',
    languages_spoken: 'Гадаад хэл',
    privacy: 'Нууцлал',
    edit_profile: 'Профайл засах',
    edit_profile_desc: 'Профайлын мэдээллээ шинэчлэх',
    basic_info: 'Үндсэн мэдээлэл',
    details: 'Дэлгэрэнгүй',
    social: 'Сошиал',
    links: 'Холбоос',
    profile_saved: 'Профайл амжилттай хадгалагдлаа!',
    profile_save_error: 'Профайл хадгалахад алдаа гарлаа.',
    cover_photo_add: 'Ковер зураг нэмэх',
    hobbies: 'Хобби',
    hobbies_placeholder: 'Жишээ нь: Уран зураг, Дуу, Аялал, Унших',
    hobbies_hint: 'Таалагддаг зүйлсээ таслалаар тусгаарлан бичнэ үү',
    privacy_settings: 'Нууцлалын тохиргоо',
    privacy_desc: 'Таны мэдээллийг хэн харахыг тохируулна уу',
    show_email: 'Имэйл хаяг',
    show_email_desc_simple: 'Таны имэйл хаягийг хэн харах',
    show_phone: 'Утасны дугаар',
    show_phone_desc_simple: 'Таны утасны дугаарыг хэн харах',
    show_online_status: 'Онлайн статус',
    show_online_status_desc_simple: 'Таны онлайн статусыг хэн харах',
    show_hobbies: 'Хобби',
    show_hobbies_desc_simple: 'Таны хоббиг хэн харах',
    email_cannot_change: 'Имэйл хаягийг өөрчлөх боломжгүй',
    enter_full_name: 'Бүтэн нэрээ оруулна уу',
    enter_phone: 'Утасны дугаараа оруулна уу',
    enter_email: 'Имэйл хаягаа оруулна уу',
    tell_about_yourself: 'Өөрийнхөө тухай тайлбар бичнэ үү',
    enter_address: 'Хаягаа оруулна уу',
    describe_experience: 'Туршлагаа тайлбарлана уу',
    comma_separated_places: 'Жишээ нь: Улаанбаатар, Хөвсгөл, Говь',
    visited_places_hint: 'Очсон газруудаа таслалаар тусгаарлан бичнэ үү',
    comma_separated_languages: 'Жишээ нь: Монгол, Англи, Хятад',
    languages_hint: 'Мэддэг хэлнүүдээ таслалаар тусгаарлан бичнэ үү',
    describe_your_services: 'Үйлчилгээний тайлбараа бичнэ үү',
    saving: 'Хадгалж байна...',
    full_name_label: 'Овог нэр',
    full_name_placeholder: 'Таны бүтэн нэр',
    phone_label: 'Утасны дугаар',
    phone_placeholder: '+976 XXXX XXXX',
    email_label: 'Имэйл хаяг',
    bio_label: 'Тухай',
    bio_placeholder: 'Өөрийгөө товч танилцуулаарай...',
    address_label: 'Байршил / Хаяг',
    address_placeholder: 'Жишээ нь: Улаанбаатар, Сүхбаатар дүүрэг',
    experience_label: 'Туршлага',
    experience_placeholder: 'Аялалын гарын авлагын туршлагаа бичнэ үү...',
    visited_places_label: 'Очсон газрууд',
    visited_places_placeholder: 'Говь, Хөвсгөл, Алтай...',
    comma_separated_hint: 'Таслалаар тусгаарлан бичнэ үү',
    languages_label: 'Ярьдаг хэлүүд',
    languages_placeholder: 'Монгол, Англи, Хятад...',
    website_label: 'Вэбсайт',
    website_placeholder: 'https://example.com',
    operating_hours_label: 'Ажлын цаг',
    operating_hours_placeholder: '09:00 - 18:00',
    service_description_label: 'Үйлчилгээний тайлбар',
    service_description_placeholder: 'Та ямар үйлчилгээ үзүүлдэг вэ...',
    privacy_settings_title: 'Нууцлалын тохиргоо',
    privacy_settings_desc: 'Таны мэдээллийг хэн харахыг удирдана уу',
    show_email_label: 'Имэйл хаяг',
    show_email_desc: 'Бусад хэрэглэгч таны имэйлийг харах эсэх',
    show_phone_label: 'Утасны дугаар',
    show_phone_desc: 'Бусад хэрэглэгч таны дугаарыг харах эсэх',
    show_online_status_label: 'Онлайн статус',
    show_online_status_desc: 'Таны онлайн байгаа эсэхийг харуулах',
    show_hobbies_label: 'Хобби',
    show_hobbies_desc: 'Таны хоббиг бусдад харуулах эсэх',
   
    provider_category: 'Байгууллагын төрөл',
    amenities: 'Тав тух & Үйлчилгээ',
    cat_tour_agency: 'Аялалын компани',
    cat_resort: 'Амралтын газар / Камп',
    cat_rental: 'Түрээсийн үйлчилгээ',
    cat_restaurant: 'Ресторан / Дэлгүүр',
    cat_transport: 'Тээврийн үйлчилгээ',
    cat_other: 'Бусад',
    am_wifi: 'WiFi',
    am_parking: 'Зогсоол',
    am_restaurant: 'Ресторан',
    am_shower: 'Шүршүүр',
    am_pool: 'Бассейн',
    am_breakfast: 'Өглөөний цай',
    am_gear: 'Аялалын хэрэгсэл',
    am_guide: 'Хөтөчтэй',
    verify_title: 'Хаяг баталгаажуулах',
    verify_desc: 'Захиалга авахын тулд та өөрийн бичиг баримтыг илгээнэ үү. Зөвхөн админ харах боломжтой.',
    id_card: 'Иргэний үнэмлэх / Паспорт',
    cert_license: 'Сертификат / Тусгай зөвшөөрөл',
    verify_hint_tour: 'Аялал жуулчлалын үйл ажиллагаа эрхлэх тусгай зөвшөөрлөө оруулна уу.',
    verify_hint_resort: 'Газрын зөвшөөрөл болон үйл ажиллагааны гэрчилгээгээ оруулна уу.',
    verify_hint_rental: 'Бизнес эрхлэх гэрчилгээгээ оруулна уу.',
    verify_hint_food: 'Эрүүл ахуйн зөвшөөрөл болон гэрчилгээгээ оруулна уу.',
    verify_hint_generic: 'Үйл ажиллагаа явуулах эрх бүхий бичиг баримтаа оруулна уу.',
    upload_doc: 'Зураг оруулах',
    submit_verify: 'Шалгуулах',
    verify_status: 'Төлөв',
    status_pending: 'Хүлээгдэж байна',
    status_approved: 'Баталгаажсан',
    status_rejected: 'Татгалзсан',
    language_exams: 'Хэлний шалгалт',
    exam_desc: 'Та мэддэг хэлнийхээ түвшинг баталгаажуулахын тулд шалгалт өгнө үү. (10 асуулт, 10 минут)',
    take_exam: 'Шалгалт өгөх',
    score: 'Оноо',
    passed: 'Тэнцсэн',
    failed: 'Тэнцээгүй',
    start_exam: 'Эхлүүлэх',
    time_remaining: 'Үлдсэн хугацаа',
    submit_exam: 'Дуусгах',
    book_now: 'Захиалах',
    message: 'Зурвас',
    reviews: 'Сэтгэгдэл',
    submit_review: 'Илгээх',
    select_date: 'Өдөр сонгох',
    guests: 'Зочид',
    payment_method: 'Төлбөрийн хэлбэр',
    total: 'Нийт',
    pay_book: 'Төлөх & Захиалах',
    processing: 'Боловсруулж байна...',
    online: 'Онлайн',
    loading: 'Уншиж байна...',
    find_locals: 'Орон нутгийн хөтөч хайх.',
    resorts_camps: 'Амралтын газар & Камп.',
    no_registered: 'Бүртгэлтэй хүн алга.',
    map_view: 'Газрын зураг',
    list_view: 'Жагсаалт',
    view_profile: 'Профайл үзэх',
    translator: 'Орчуулагч',
    translate_desc: 'AI ашиглан бодит цагт орчуулах',
    type_to_translate: 'Орчуулах зүйлээ бичнэ үү...',
    listening: 'Сонсож байна...',
    tap_to_speak: 'Ярих',
    translating: 'Орчуулж байна...',
    account_pending_action: 'Таны бүртгэл хүлээгдэж байгаа тул энэ үйлдлийг хийх боломжгүй. Админ баталгаажуулахыг хүлээнэ үү.',
    provider_pending_action: 'Энэ хэрэглэгч баталгаажаагүй байгаа тул захиалга авах боломжгүй.',
    ai_powered: 'AI-аар ажилладаг',
    copied: 'Хуулагдлаа!',
    dashboard: 'Хянах самбар',
    saved: 'Хадгалсан',
    add_post: 'Пост нэмэх',
    followers: 'Дагагч',
    following: 'Дагасан',
    travel_gallery: 'Аялалын цомог',
    my_services: 'Миний үйлчилгээ',
    my_travels: 'Миний аялалууд',
    total_earnings: 'Нийт орлого',
    total_bookings: 'Нийт захиалга',
    bookings_list: 'Захиалгын жагсаалт',
    no_active_bookings: 'Идэвхтэй захиалга алга.',
    status_confirmed: 'Баталгаажсан',
    status_cancelled: 'Цуцлагдсан',
    where_to_travel: 'Хаашаа аялах вэ?',
    days: 'Хэдэн өдөр',
    budget_economic: 'Хямд',
    budget_standard: 'Дундаж',
    budget_luxury: 'Тансаг',
    generate_plan: 'Төлөвлөгөө гаргах',
    itinerary: 'Аялалын хөтөлбөр',
    ai_planner: 'AI Төлөвлөгч',
    status_passed: 'Тэнцсэн',
    status_failed: 'Тэнцээгүй',
    messages: 'Зурвасууд',
    no_messages: 'Зурвас алга.',
    start_conversation_hint: 'Хэрэглэгчийн профайл руу орж чат бичнэ үү.',
    confirm_delete_msg: 'Энэ мессежийг устгах уу?',
    confirm_delete_chat: 'Бүх чатын түүхийг устгах уу? Энэ үйлдлийг буцаах боломжгүй.',
    send_failed: 'Илгээж чадсангүй',
    backend_error: 'Серверийн алдаа',
    mic_error: 'Микрофон ашиглах боломжгүй',
    upload_failed: 'Файл илгээхэд алдаа гарлаа',
    you_blocked_user: 'Та энэ хэрэглэгчийг блоклосон байна',
    user_blocked_you: 'Та энэ хэрэглэгчид блоклогдсон байна',
    message_placeholder: 'Зурвас бичих...',
    delete_chat: 'Чат устгах',
    delete: 'Устгах',
    voice_call: 'Дуут дуудлага',
    video_call: 'Видео дуудлага',
    connecting: 'Холбогдож байна...',
    video_calling: 'Видео дуудлага...',
    voice_calling: 'Дуут дуудлага...',
    mute: 'Чимээгүй',
    mic: 'Микрофон',
    camera: 'Камер',
    speaker: 'Яригч',
    end_call: 'Дуусгах',
    notifications: 'Мэдэгдэл',
    no_notifications: 'Мэдэгдэл алга',
    notif_like: 'таны пост дээр like дарлаа.',
    notif_review: 'танд сэтгэгдэл үлдээлээ.',
    notif_approved: 'таны бүртгэлийг баталгаажууллаа! Бүх эрх нээгдсэн.',
    notif_rejected: 'таны бүртгэлээс татгалзлаа. Мэдээллээ засаад дахин илгээнэ үү.',
    notif_follow: 'таныг дагаж эхэллээ.',
    notif_call: 'тан руу залгаж байна...',
    notif_comment: 'таны пост дээр сэтгэгдэл бичлээ.',
    share_travel_note: 'Аялалын тэмдэглэл, туршлагаа хуваалцаарай...',
    is_service: 'Үйлчилгээ (Service)',
    service_name: 'Үйлчилгээний нэр',
    price: 'Үнэ (₮)',
    capacity: 'Хүний тоо',
    incoming_video_call: 'Видео дуудлага ирж байна...',
    incoming_voice_call: 'Дуут дуудлага ирж байна...',
    accept: 'Авах',
    decline: 'Татгалзах',
    missed_video_call: 'Хариулаагүй видео дуудлага',
    missed_voice_call: 'Хариулаагүй дуут дуудлага',
    video_call_log: 'Видео дуудлага',
    voice_call_log: 'Дуут дуудлага',
    online_status: 'Онлайн',
    language_name: 'Mongolian',
    service_stats: 'Үйлчилгээний статистик',
    clients_count: 'Хүн',
    income: 'Орлого',
    first_name: 'Нэр',
    last_name: 'Овог',
    birth_date: 'Төрсөн он сар өдөр',
    referral_source: 'Аппыг хаанаас мэдсэн бэ?',
    ref_social: 'Сошиал медиа (FB, IG)',
    ref_friend: 'Найз нөхөд',
    ref_ad: 'Зар сурталчилгаа',
    ref_other: 'Бусад',
    step_n_of_m: 'Алхам {n} / {m}',
    next: 'Дараах',
    back: 'Буцах',
    // Landing page translations
    hero_badge: 'Монголын шилдэг аялалын платформ',
    hero_subtitle: 'Мэргэжлийн хөтөч олох, аялал захиалах, байгалийн гайхамшигт газруудыг нээн илрүүлэх — бүгдийг нэг дороос.',
    stat_guides: 'Хөтөч',
    stat_travelers: 'Аялагчид',
    stat_destinations: 'Газрууд',
    stat_languages: 'Хэл',
    get_started: 'Одоо эхлэх',
    services_title: 'Үйлчилгээнүүд',
    services_desc: 'VIP Travel платформоор дамжуулан аяллынхаа бүх хэрэгцээг хангаарай.',
    service_find_guide: 'Хөтөч олох',
    service_find_guide_desc: 'Монгол болон гадаад хөтөчдийн жагсаалтаас шинжлэн харьцуулж, өөрт тохирох хөтчийг сонго. Үнэлгээ, тайлбарыг харж шийдвэр гарга.',
    service_book_tour: 'Аялал захиалах',
    service_book_tour_desc: 'Хөтөчтэй шууд холбогдож аялал захиалах. QPay, SocialPay болон картаар хялбар төлбөр тооцоо хийх боломж.',
    service_interactive_map: 'Газрын зураг',
    service_interactive_map_desc: 'Mapbox технологиор дэмжигдсэн интерактив газрын зураг. Хөтөч болон үйлчилгээ үзүүлэгчдийн байршлыг бодит цагт харах.',
    view_all_services: 'Бүх үйлчилгээг үзэх',
    all_services_title: 'Бүх үйлчилгээнүүд',
    all_services_desc: 'VIP Travel платформын бүх үйлчилгээ',
    service_translator: 'Орчуулагч',
    service_translator_desc: 'Хөтөч болон аялагч хоорондын харилцааг 10 хэлд дэмжих орчуулах функц. Хэлний саад бус аялаарай.',
    service_chat_calls: 'Мессеж & Дуудлага',
    service_chat_calls_desc: 'Аялагч болон хөтөч хооронд шууд чат, видео дуудлага. Аюулгүй, бодит цагийн харилцаа Cloudflare Calls дамжуулан.',
    service_social_feed: 'Нийгмийн сүлжээ',
    service_social_feed_desc: 'Аяллын мэдрэмжийг хуваалц, зураг видео нийтлэх, сэтгэгдэл үлдээх. Аялалчдын нийгэмлэгт нэгдэ.',
    service_provider_services: 'Байгууллагын үйлчилгээ',
    service_provider_services_desc: 'Камп, рашаан, тээвэр, ресторан, түрээс зэрэг байгууллагын үйлчилгээг нэг дороос захиалах боломж.',
    service_guide_verification: 'Хөтчийн баталгаажуулалт',
    service_guide_verification_desc: 'Бүх хөтөчид баримт бичиг, гэрчилгээгээр баталгаажсан. Аюулгүй, итгэлтэй аялалын баталгаа.',
    service_live_streaming: 'Шууд дамжуулалт',
    service_live_streaming_desc: 'Хөтөч болон байгалийн газруудаас шууд дамжуулалт үзэх, аялалаа урьдчилан таньж мэдэх боломж.',
    footer_copyright: '© 2026 VIP Travel. Бүх эрх хуулиар хамгаалагдсан.',
    footer_terms: 'Үйлчилгээний нөхцөл'
  },
  en: {
    welcome_back: 'Welcome to CJ Travel',
    login_subtitle: 'Log in to continue',
    email: 'Email',
    password: 'Password',
    login: 'Log In',
    logging_in: 'Logging in...',
    forgot_password: 'Forgot Password?',
    reset_password: 'Reset Password',
    send_recovery_link: 'Send Code',
    enter_recovery_code: 'Recovery Code',
    new_password: 'New Password',
    update_password: 'Update Password',
    code_sent: 'Recovery code sent to email (Use: 123456)',
    phone_verification: 'Phone Verification',
    verify_now: 'Verify Now',
    verified: 'Verified',
    unverified: 'Unverified',
    send_code: 'Send Code',
    enter_code: 'Enter Code',
    verify: 'Verify',
    phone_code_sent: 'Code sent to your phone (Use: 5555)',
    invalid_code: 'Invalid Code',
    success_verified: 'Successfully Verified!',
    no_account: "Don't have an account?",
    sign_up: 'Sign Up',
    create_account: 'Create Account',
    choose_role: 'Choose Account Type',
    how_will_use: 'How will you use the platform?',
    traveler: 'Traveler',
    traveler_desc: 'Plan trips & explore destinations.',
    guide: 'Tour Guide',
    guide_desc: 'Lead tours & share expertise.',
    provider: 'Provider',
    provider_desc: 'Manage camps & services.',
    already_account: 'Already have an account?',
    full_name: 'Full Name',
    phone: 'Phone',
    creating_account: 'Creating Account...',
    feed: 'Feed',
    guides: 'Guides',
    providers: 'Providers',
    profile: 'Profile',
    search_placeholder: 'Search guides, providers, or posts...',
    no_results: 'No results found.',
    no_posts: 'No posts yet. Be the first to share!',
    create_post: 'Create Post',
    share_experience: 'Share your travel experience...',
    post: 'Post',
    posting: 'Posting...',
    cancel: 'Cancel',
    photo_video: 'Photo/Video',
    promote_service: 'Promote Service/Camp',
    info: 'Info',
    my_bookings: 'My Bookings',
    edit: 'Edit',
    save_changes: 'Save Changes',
    location: 'Location',
    experience: 'Experience',
    visited_places: 'Visited Places',
    service_desc: 'Service Description',
    public: 'Public?',
    logout: 'Log Out',
    verification: 'Verification',
    languages_spoken: 'Languages Spoken',
    guiding_locations: 'Guiding Locations',
    provider_category: 'Business Category',
    operating_hours: 'Operating Hours',
    website: 'Website',
    amenities: 'Amenities',
    cat_tour_agency: 'Tour Agency',
    cat_resort: 'Resort / Camp',
    cat_rental: 'Rental Service',
    cat_restaurant: 'Restaurant / Shop',
    cat_transport: 'Transport',
    cat_other: 'Other',
    am_wifi: 'WiFi',
    am_parking: 'Parking',
    am_restaurant: 'Restaurant',
    am_shower: 'Shower',
    am_pool: 'Swimming Pool',
    am_breakfast: 'Breakfast',
    am_gear: 'Camping Gear',
    am_guide: 'Guided Tours',
    verify_title: 'Account Verification',
    verify_desc: 'Submit your documents to accept bookings. Only visible to Admin.',
    id_card: 'Government ID / Passport',
    cert_license: 'Certificate / Business License',
    verify_hint_tour: 'Please upload your Tour Operator License.',
    verify_hint_resort: 'Please upload Land Use Permit and Operation Certificate.',
    verify_hint_rental: 'Please upload your Business Registration Certificate.',
    verify_hint_food: 'Please upload Hygiene Permit and Business License.',
    verify_hint_generic: 'Please upload official documents proving your business operation.',
    upload_doc: 'Upload Document',
    submit_verify: 'Submit for Review',
    verify_status: 'Status',
    status_pending: 'Pending',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    language_exams: 'Language Exams',
    exam_desc: 'Take an exam to verify your language proficiency. (10 questions, 10 minutes)',
    take_exam: 'Take Exam',
    score: 'Score',
    passed: 'Passed',
    failed: 'Failed',
    start_exam: 'Start Exam',
    time_remaining: 'Time Remaining',
    submit_exam: 'Submit',
    book_now: 'Book Now',
    message: 'Message',
    reviews: 'Reviews',
    submit_review: 'Submit Review',
    select_date: 'Select Date',
    guests: 'Guests',
    payment_method: 'Payment Method',
    total: 'Total',
    pay_book: 'Pay & Book',
    processing: 'Processing...',
    online: 'Online',
    loading: 'Loading...',
    find_locals: 'Find locals to show you around.',
    resorts_camps: 'Resorts, Camps & Services.',
    no_registered: 'No one registered yet.',
    map_view: 'Map View',
    list_view: 'List View',
    view_profile: 'View Profile',
    translator: 'Translator',
    translate_desc: 'Real-time AI translation',
    type_to_translate: 'Type to translate...',
    listening: 'Listening...',
    tap_to_speak: 'Tap to speak',
    translating: 'Translating...',
    account_pending_action: 'Your account is pending approval. You cannot perform this action yet.',
    provider_pending_action: 'This user is pending approval and cannot accept bookings yet.',
    ai_powered: 'AI Powered',
    copied: 'Copied!',
    dashboard: 'Dashboard',
    saved: 'Saved',
    add_post: 'Add Post',
    followers: 'Followers',
    following: 'Following',
    travel_gallery: 'Travel Gallery',
    my_services: 'My Services',
    my_travels: 'My Travels',
    total_earnings: 'Total Earnings',
    total_bookings: 'Total Bookings',
    bookings_list: 'Bookings List',
    no_active_bookings: 'No active bookings.',
    status_confirmed: 'Confirmed',
    status_cancelled: 'Cancelled',
    where_to_travel: 'Where to travel?',
    days: 'Days',
    budget_economic: 'Economic',
    budget_standard: 'Standard',
    budget_luxury: 'Luxury',
    generate_plan: 'Generate Plan',
    itinerary: 'Itinerary',
    ai_planner: 'AI Planner',
    status_passed: 'Passed',
    status_failed: 'Failed',
    messages: 'Messages',
    no_messages: 'No messages yet.',
    start_conversation_hint: 'Start a conversation from a user profile.',
    confirm_delete_msg: 'Delete this message?',
    confirm_delete_chat: 'Delete entire chat history? This cannot be undone.',
    send_failed: 'Failed to send',
    backend_error: 'Server error',
    mic_error: 'Microphone access denied',
    upload_failed: 'Upload failed',
    you_blocked_user: 'You have blocked this user',
    user_blocked_you: 'You have been blocked by this user',
    message_placeholder: 'Message...',
    delete_chat: 'Delete Chat',
    delete: 'Delete',
    voice_call: 'Voice Call',
    video_call: 'Video Call',
    connecting: 'Connecting...',
    video_calling: 'Video Calling...',
    voice_calling: 'Voice Calling...',
    mute: 'Mute',
    mic: 'Mic',
    camera: 'Camera',
    speaker: 'Speaker',
    end_call: 'End Call',
    notifications: 'Notifications',
    no_notifications: 'No notifications',
    notif_like: 'liked your post.',
    notif_review: 'gave you a review.',
    notif_approved: 'approved your account! All features unlocked.',
    notif_rejected: 'rejected your account. Please update and resubmit.',
    notif_follow: 'started following you.',
    notif_call: 'is calling you...',
    notif_comment: 'commented on your post.',
    share_travel_note: 'Share your travel notes and experience...',
    is_service: 'Service',
    service_name: 'Service Name',
    price: 'Price',
    capacity: 'Capacity',
    incoming_video_call: 'Incoming video call...',
    incoming_voice_call: 'Incoming voice call...',
    accept: 'Accept',
    decline: 'Decline',
    missed_video_call: 'Missed video call',
    missed_voice_call: 'Missed voice call',
    video_call_log: 'Video call',
    voice_call_log: 'Voice call',
    online_status: 'Online',
    language_name: 'English',
    service_stats: 'Service Statistics',
    clients_count: 'Clients',
    income: 'Income',
    first_name: 'First Name',
    last_name: 'Last Name',
    birth_date: 'Date of Birth',
    referral_source: 'How did you hear about us?',
    ref_social: 'Social Media',
    ref_friend: 'Friend/Family',
    ref_ad: 'Advertisement',
    ref_other: 'Other',
    step_n_of_m: 'Step {n} of {m}',
    next: 'Next',
    back: 'Back',
    // Landing page translations
    hero_badge: "Mongolia's Premier Travel Platform",
    hero_subtitle: 'Find professional guides, book tours, discover breathtaking destinations — all in one place.',
    stat_guides: 'Guides',
    stat_travelers: 'Travelers',
    stat_destinations: 'Destinations',
    stat_languages: 'Languages',
    get_started: 'Get Started',
    services_title: 'Services',
    services_desc: 'Meet all your travel needs through the VIP Travel platform.',
    service_find_guide: 'Find a Guide',
    service_find_guide_desc: 'Browse and compare local and international guides, view ratings and reviews to find your perfect match.',
    service_book_tour: 'Book a Tour',
    service_book_tour_desc: 'Connect directly with guides to book tours. Easy payment via QPay, SocialPay or card.',
    service_interactive_map: 'Interactive Map',
    service_interactive_map_desc: 'Powered by Mapbox. See guides and service providers in real time on an interactive map.',
    view_all_services: 'View All Services',
    all_services_title: 'All Services',
    all_services_desc: 'All services of VIP Travel platform',
    service_translator: 'Translator',
    service_translator_desc: 'Built-in translation supporting 10 languages for seamless communication between guides and travelers.',
    service_chat_calls: 'Chat & Calls',
    service_chat_calls_desc: 'Direct messaging and video calls between travelers and guides via Cloudflare Calls.',
    service_social_feed: 'Social Feed',
    service_social_feed_desc: 'Share your travel moments, post photos and videos, leave reviews, join the travel community.',
    service_provider_services: 'Provider Services',
    service_provider_services_desc: 'Book camps, spas, transport, restaurants and rental services all in one place.',
    service_guide_verification: 'Guide Verification',
    service_guide_verification_desc: 'All guides verified with official documents and certificates. Safe, trusted travel guaranteed.',
    service_live_streaming: 'Live Streaming',
    service_live_streaming_desc: 'Watch live streams from guides and locations to preview your adventure before booking.',
    footer_copyright: '© 2026 VIP Travel. All rights reserved.',
    footer_terms: 'Terms of Service'
  },
  cn: {
    welcome_back: '欢迎来到 CJ Travel',
    login_subtitle: '登录以继续',
    email: '电子邮件',
    password: '密码',
    login: '登录',
    logging_in: '登录中...',
    forgot_password: '忘记密码？',
    reset_password: '重置密码',
    send_recovery_link: '发送代码',
    enter_recovery_code: '恢复代码',
    new_password: '新密码',
    update_password: '更新密码',
    code_sent: '恢复代码已发送至邮箱（使用：123456）',
    phone_verification: '电话验证',
    verify_now: '立即验证',
    verified: '已验证',
    unverified: '未验证',
    send_code: '发送代码',
    enter_code: '输入代码',
    verify: '验证',
    phone_code_sent: '代码已发送至您的手机（使用：5555）',
    invalid_code: '代码无效',
    success_verified: '验证成功！',
    no_account: '还没有账号？',
    sign_up: '注册',
    create_account: '创建账号',
    choose_role: '选择账户类型',
    how_will_use: '您将如何使用该平台？',
    traveler: '游客',
    traveler_desc: '计划旅行和探索目的地。',
    guide: '导游',
    guide_desc: '带领旅行和分享经验。',
    provider: '服务商',
    provider_desc: '管理营地和服务。',
    already_account: '已有账号？',
    full_name: '全名',
    phone: '电话',
    creating_account: '创建中...',
    feed: '动态',
    guides: '导游',
    providers: '服务商',
    profile: '个人资料',
    search_placeholder: '搜索导游、服务商或帖子...',
    no_results: '未找到结果。',
    no_posts: '暂无帖子。成为第一个分享的人！',
    create_post: '发布帖子',
    share_experience: '分享您的旅行经历...',
    post: '发布',
    posting: '发布中...',
    cancel: '取消',
    photo_video: '照片/视频',
    promote_service: '推广服务/营地',
    info: '信息',
    my_bookings: '我的预订',
    edit: '编辑',
    save_changes: '保存更改',
    location: '位置',
    experience: '经验',
    visited_places: '去过的地方',
    service_desc: '服务描述',
    public: '公开？',
    logout: '退出',
    verification: '验证',
    languages_spoken: '口语语言',
    guiding_locations: '导游地点',
    provider_category: '业务类别',
    operating_hours: '营业时间',
    website: '网站',
    amenities: '设施',
    cat_tour_agency: '旅行社',
    cat_resort: '度假村 / 营地',
    cat_rental: '租赁服务',
    cat_restaurant: '餐厅 / 商店',
    cat_transport: '运输',
    cat_other: '其他',
    am_wifi: '无线上网',
    am_parking: '停車處',
    am_restaurant: '餐厅',
    am_shower: '淋浴',
    am_pool: '游泳池',
    am_breakfast: '早餐',
    am_gear: '露营装备',
    am_guide: '导游',
    verify_title: '账户验证',
    verify_desc: '提交您的文件以接受预订。 仅管理员可见。',
    id_card: '身份证 / 护照',
    cert_license: '证书 / 营业执照',
    verify_hint_tour: '请上传您的旅行社经营许可证。',
    verify_hint_resort: '请上传土地使用证和经营许可证。',
    verify_hint_rental: '请上传您的商业登记证。',
    verify_hint_food: '请上传卫生许可证和营业执照。',
    verify_hint_generic: '请上传证明您业务运营的官方文件。',
    upload_doc: '上传文件',
    submit_verify: '提交审核',
    verify_status: '状态',
    status_pending: '待审核',
    status_approved: '已批准',
    status_rejected: '已拒绝',
    language_exams: '语言考试',
    exam_desc: '参加考试以验证您的语言能力。（10个问题，10分钟）',
    take_exam: '参加考试',
    score: '分数',
    passed: '通过',
    failed: '失败',
    start_exam: '开始考试',
    time_remaining: '剩余时间',
    submit_exam: '提交',
    book_now: '立即预订',
    message: '发消息',
    reviews: '评论',
    submit_review: '提交评论',
    select_date: '选择日期',
    guests: '人数',
    payment_method: '支付方式',
    total: '总计',
    pay_book: '支付并预订',
    processing: '处理中...',
    online: '在线',
    loading: '加载中...',
    find_locals: '寻找当地人带您游览。',
    resorts_camps: '度假村、营地和服务。',
    no_registered: '暂无注册。',
    map_view: '地图视图',
    list_view: '列表视图',
    view_profile: '查看资料',
    translator: '翻译器',
    translate_desc: '实时 AI 翻译',
    type_to_translate: '输入翻译内容...',
    listening: '正在听...',
    tap_to_speak: '点击说话',
    translating: '翻译中...',
    account_pending_action: '您的帐户正在等待批准。您暂时无法执行此操作。',
    provider_pending_action: '该用户正在等待批准，暂时无法接受预订。',
    ai_powered: 'AI 驱动',
    copied: '已复制！',
    dashboard: '仪表板',
    saved: '已保存',
    add_post: '发布帖子',
    followers: '关注者',
    following: '关注中',
    travel_gallery: '旅行相册',
    my_services: '我的服务',
    my_travels: '我的旅行',
    total_earnings: '总收入',
    total_bookings: '总预订',
    bookings_list: '预订列表',
    no_active_bookings: '无有效预订。',
    status_confirmed: '已确认',
    status_cancelled: '已取消',
    where_to_travel: '去哪里旅行？',
    days: '天数',
    budget_economic: '经济',
    budget_standard: '标准',
    budget_luxury: '豪华',
    generate_plan: '生成计划',
    itinerary: '行程',
    ai_planner: 'AI 规划师',
    status_passed: '通过',
    status_failed: '未通过',
    messages: '消息',
    no_messages: '暂无消息。',
    start_conversation_hint: '从用户资料开始对话。',
    confirm_delete_msg: '删除此消息？',
    confirm_delete_chat: '删除整个聊天记录？此操作无法撤消。',
    send_failed: '发送失败',
    backend_error: '服务器错误',
    mic_error: '无法访问麦克风',
    upload_failed: '上传失败',
    you_blocked_user: '您已屏蔽此用户',
    user_blocked_you: '您已被此用户屏蔽',
    message_placeholder: '消息...',
    delete_chat: '删除聊天',
    delete: '删除',
    voice_call: '语音通话',
    video_call: '视频通话',
    connecting: '正在连接...',
    video_calling: '视频呼叫中...',
    voice_calling: '语音呼叫中...',
    mute: '静音',
    mic: '麦克风',
    camera: '相机',
    speaker: '扬声器',
    end_call: '结束通话',
    notifications: '通知',
    no_notifications: '暂无通知',
    notif_like: '赞了你的帖子。',
    notif_review: '给你写了评论。',
    notif_approved: '批准了您的帐户！所有功能已解锁。',
    notif_rejected: '拒绝了您的帐户。请更新并重新提交。',
    notif_follow: '开始关注你。',
    notif_call: '正在呼叫你...',
    notif_comment: '评论了你的帖子。',
    share_travel_note: '分享您的旅行笔记和经验...',
    is_service: '服务',
    service_name: '服务名称',
    price: '价格',
    capacity: '容量',
    incoming_video_call: '视频通话来电...',
    incoming_voice_call: '语音通话来电...',
    accept: '接听',
    decline: '拒绝',
    missed_video_call: '未接视频通话',
    missed_voice_call: '未接语音通话',
    video_call_log: '视频通话',
    voice_call_log: '语音通话',
    online_status: '在线',
    language_name: 'Chinese',
    // Landing page translations
    hero_badge: '蒙古最佳旅游平台',
    hero_subtitle: '寻找专业导游，预订旅游，探索令人叹为观止的目的地——一站式服务。',
    stat_guides: '导游',
    stat_travelers: '旅行者',
    stat_destinations: '目的地',
    stat_languages: '语言',
    get_started: '立即开始',
    services_title: '服务',
    services_desc: '通过VIP Travel平台满足您所有的旅行需求。',
    view_all_services: '查看所有服务',
    all_services_title: '所有服务',
    all_services_desc: 'VIP Travel平台的所有服务',
    footer_terms: '服务条款',
    // Service translations
    service_find_guide: '寻找导游',
    service_find_guide_desc: '浏览并比较本地和国际导游，查看评分和评论以找到最适合您的导游。',
    service_book_tour: '预订旅游',
    service_book_tour_desc: '直接与导游联系预订旅游。通过QPay、SocialPay或银行卡轻松付款。',
    service_interactive_map: '互动地图',
    service_interactive_map_desc: '由Mapbox提供支持。在互动地图上实时查看导游和服务提供商。',
    service_translator: '翻译器',
    service_translator_desc: '内置翻译支持10种语言，实现导游和旅行者之间的无缝沟通。',
    service_chat_calls: '聊天和通话',
    service_chat_calls_desc: '通过Cloudflare Calls在旅行者和导游之间进行直接消息传递和视频通话。',
    service_social_feed: '社交动态',
    service_social_feed_desc: '分享您的旅行时刻，发布照片和视频，留下评论，加入旅行社区。',
    service_provider_services: '服务提供商',
    service_provider_services_desc: '在一个地方预订营地、温泉、交通、餐厅和租赁服务。',
    service_guide_verification: '导游认证',
    service_guide_verification_desc: '所有导游均经过官方文件和证书验证。保证安全、可信赖的旅行。',
    service_live_streaming: '直播',
    service_live_streaming_desc: '观看导游和景点的直播，提前预览您的冒险。'
  },
  ru: {
    welcome_back: 'С возвращением',
    login_subtitle: 'Войти для продолжения',
    email: 'Email',
    password: 'Пароль',
    login: 'Войти',
    logging_in: 'Вход...',
    forgot_password: 'Забыли пароль?',
    reset_password: 'Сброс пароля',
    send_recovery_link: 'Отправить код',
    enter_recovery_code: 'Код восстановления',
    new_password: 'Новый пароль',
    update_password: 'Обновить пароль',
    code_sent: 'Код отправлен на почту (Например: 123456)',
    phone_verification: 'Подтверждение телефона',
    verify_now: 'Подтвердить',
    verified: 'Подтверждено',
    unverified: 'Не подтверждено',
    send_code: 'Отправить код',
    enter_code: 'Введите код',
    verify: 'Проверить',
    phone_code_sent: 'Код отправлен на телефон (Например: 5555)',
    invalid_code: 'Неверный код',
    success_verified: 'Успешно подтверждено!',
    no_account: 'Нет аккаунта?',
    sign_up: 'Регистрация',
    create_account: 'Создать аккаунт',
    choose_role: 'Выберите роль',
    how_will_use: 'Как вы будете использовать платформу?',
    traveler: 'Путешественник',
    traveler_desc: 'Планируйте поездки.',
    guide: 'Гид',
    guide_desc: 'Проводите туры.',
    provider: 'Провайдер',
    provider_desc: 'Управляйте услугами.',
    already_account: 'Есть аккаунт?',
    full_name: 'ФИО',
    phone: 'Телефон',
    creating_account: 'Создание...',
    feed: 'Лента',
    guides: 'Гиды',
    providers: 'Услуги',
    profile: 'Профиль',
    search_placeholder: 'Поиск...',
    no_results: 'Ничего не найдено.',
    no_posts: 'Постов пока нет.',
    create_post: 'Создать пост',
    share_experience: 'Поделитесь опытом...',
    post: 'Опубликовать',
    posting: 'Публикация...',
    cancel: 'Отмена',
    photo_video: 'Фото/Видео',
    promote_service: 'Продвигать услугу',
    info: 'Инфо',
    my_bookings: 'Мои брони',
    edit: 'Изменить',
    save_changes: 'Сохранить',
    location: 'Местоположение',
    experience: 'Опыт',
    visited_places: 'Посещенные места',
    service_desc: 'Описание услуги',
    public: 'Публичный?',
    logout: 'Выйти',
    verification: 'Верификация',
    languages_spoken: 'Языки',
    guiding_locations: 'Локации гида',
    provider_category: 'Категория',
    operating_hours: 'Время работы',
    website: 'Сайт',
    amenities: 'Удобства',
    cat_tour_agency: 'Турагентство',
    cat_resort: 'Курорт / Лагерь',
    cat_rental: 'Прокат',
    cat_restaurant: 'Ресторан / Магазин',
    cat_transport: 'Транспорт',
    cat_other: 'Другое',
    am_wifi: 'WiFi',
    am_parking: 'Парковка',
    am_restaurant: 'Ресторан',
    am_shower: 'Душ',
    am_pool: 'Бассейн',
    am_breakfast: 'Завтрак',
    am_gear: 'Снаряжение',
    am_guide: 'Гиды',
    verify_title: 'Подтверждение аккаунта',
    verify_desc: 'Загрузите документы для приема бронирований. Доступно только админу.',
    id_card: 'Паспорт / ID карта',
    cert_license: 'Сертификат / Лицензия',
    verify_hint_tour: 'Загрузите лицензию туроператора.',
    verify_hint_resort: 'Загрузите разрешение на землю.',
    verify_hint_rental: 'Загрузите бизнес-регистрацию.',
    verify_hint_food: 'Загрузите санитарное разрешение.',
    verify_hint_generic: 'Загрузите официальные документы.',
    upload_doc: 'Загрузить',
    submit_verify: 'Отправить',
    verify_status: 'Статус',
    status_pending: 'В ожидании',
    status_approved: 'Одобрено',
    status_rejected: 'Отклонено',
    language_exams: 'Языковые тесты',
    exam_desc: 'Пройдите тест. (10 вопросов, 10 минут)',
    take_exam: 'Пройти тест',
    score: 'Баллы',
    passed: 'Сдано',
    failed: 'Не сдано',
    start_exam: 'Начать',
    time_remaining: 'Время',
    submit_exam: 'Завершить',
    book_now: 'Забронировать',
    message: 'Сообщение',
    reviews: 'Отзывы',
    submit_review: 'Оставить отзыв',
    select_date: 'Выбрать дату',
    guests: 'Гости',
    payment_method: 'Способ оплаты',
    total: 'Итого',
    pay_book: 'Оплатить',
    processing: 'Обработка...',
    online: 'Онлайн',
    loading: 'Загрузка...',
    find_locals: 'Найдите местных гидов.',
    resorts_camps: 'Курорты и услуги.',
    no_registered: 'Никого нет.',
    map_view: 'Карта',
    list_view: 'Список',
    view_profile: 'Профиль',
    translator: 'Переводчик',
    translate_desc: 'AI перевод',
    type_to_translate: 'Пишите...',
    listening: 'Слушаю...',
    tap_to_speak: 'Говорить',
    translating: 'Перевод...',
    account_pending_action: 'Аккаунт на проверке.',
    provider_pending_action: 'Пользователь на проверке.',
    ai_powered: 'Работает на AI',
    copied: 'Скопировано!',
    dashboard: 'Панель',
    saved: 'Сохранено',
    add_post: 'Добавить пост',
    followers: 'Подписчики',
    following: 'Подписки',
    travel_gallery: 'Галерея',
    my_services: 'Мои услуги',
    my_travels: 'Мои путешествия',
    total_earnings: 'Доход',
    total_bookings: 'Всего бронирований',
    bookings_list: 'Список бронирований',
    no_active_bookings: 'Нет активных броней.',
    status_confirmed: 'Подтверждено',
    status_cancelled: 'Отменено',
    where_to_travel: 'Куда поехать?',
    days: 'Дни',
    budget_economic: 'Эконом',
    budget_standard: 'Стандарт',
    budget_luxury: 'Люкс',
    generate_plan: 'Создать план',
    itinerary: 'Маршрут',
    ai_planner: 'AI Планировщик',
    status_passed: 'Сдано',
    status_failed: 'Не сдано',
    messages: 'Сообщения',
    no_messages: 'Сообщений пока нет.',
    start_conversation_hint: 'Начните разговор из профиля пользователя.',
    confirm_delete_msg: 'Удалить это сообщение?',
    confirm_delete_chat: 'Удалить всю историю чата? Это действие нельзя отменить.',
    send_failed: 'Не удалось отправить',
    backend_error: 'Ошибка сервера',
    mic_error: 'Доступ к микрофону запрещен',
    upload_failed: 'Ошибка загрузки',
    you_blocked_user: 'Вы заблокировали этого пользователя',
    user_blocked_you: 'Вы заблокированы этим пользователем',
    message_placeholder: 'Сообщение...',
    delete_chat: 'Удалить чат',
    delete: 'Удалить',
    voice_call: 'Голосовой вызов',
    video_call: 'Видеовызов',
    connecting: 'Подключение...',
    video_calling: 'Видеовызов...',
    voice_calling: 'Голосовой вызов...',
    mute: 'Мут',
    mic: 'Микрофон',
    camera: 'Камера',
    speaker: 'Динамик',
    end_call: 'Завершить',
    notifications: 'Уведомления',
    no_notifications: 'Нет уведомлений',
    notif_like: 'понравился ваш пост.',
    notif_review: 'оставил вам отзыв.',
    notif_approved: 'одобрил ваш аккаунт! Все функции разблокированы.',
    notif_rejected: 'отклонил ваш аккаунт. Пожалуйста, обновите и отправьте снова.',
    notif_follow: 'начал читать вас.',
    notif_call: 'звонит вам...',
    notif_comment: 'прокомментировал ваш пост.',
    share_travel_note: 'Поделитесь своими заметками о путешествиях...',
    is_service: 'Услуга',
    service_name: 'Название услуги',
    price: 'Цена',
    capacity: 'Вместимость',
    incoming_video_call: 'Входящий видеовызов...',
    incoming_voice_call: 'Входящий голосовой вызов...',
    accept: 'Принять',
    decline: 'Отклонить',
    missed_video_call: 'Пропущенный видеовызов',
    missed_voice_call: 'Пропущенный голосовой вызов',
    video_call_log: 'Видеовызов',
    voice_call_log: 'Голосовой вызов',
    online_status: 'Онлайн',
    language_name: 'Russian',
    // Landing page translations
    hero_badge: 'Лучшая туристическая платформа Монголии',
    hero_subtitle: 'Найдите профессионального гида, забронируйте туры, откройте для себя захватывающие направления — всё в одном месте.',
    stat_guides: 'Гиды',
    stat_travelers: 'Путешественники',
    stat_destinations: 'Направления',
    stat_languages: 'Языков',
    get_started: 'Начать',
    services_title: 'Услуги',
    services_desc: 'Удовлетворите все свои туристические потребности через платформу VIP Travel.',
    view_all_services: 'Посмотреть все услуги',
    all_services_title: 'Все услуги',
    all_services_desc: 'Все услуги платформы VIP Travel',
    footer_terms: 'Условия использования',
    // Service translations
    service_find_guide: 'Найти гида',
    service_find_guide_desc: 'Просматривайте и сравнивайте местных и международных гидов, читайте отзывы.',
    service_book_tour: 'Забронировать тур',
    service_book_tour_desc: 'Напрямую свяжитесь с гидами для бронирования туров. Оплата через QPay, SocialPay или карту.',
    service_interactive_map: 'Интерактивная карта',
    service_interactive_map_desc: 'На базе Mapbox. Смотрите гидов и провайдеров услуг в режиме реального времени.',
    service_translator: 'Переводчик',
    service_translator_desc: 'Встроенный перевод поддерживает 10 языков для беспрепятственного общения.',
    service_chat_calls: 'Чат и звонки',
    service_chat_calls_desc: 'Прямые сообщения и видеозвонки через Cloudflare Calls.',
    service_social_feed: 'Социальная лента',
    service_social_feed_desc: 'Делитесь моментами путешествий, публикуйте фото и видео, оставляйте отзывы.',
    service_provider_services: 'Услуги провайдеров',
    service_provider_services_desc: 'Бронируйте кемпинги, спа, транспорт, рестораны и аренду в одном месте.',
    service_guide_verification: 'Верификация гидов',
    service_guide_verification_desc: 'Все гиды верифицированы официальными документами и сертификатами.',
    service_live_streaming: 'Прямые трансляции',
    service_live_streaming_desc: 'Смотрите прямые трансляции от гидов и мест для предварительного знакомства.'
  },
  ja: {
    welcome_back: 'おかえりなさい',
    login_subtitle: 'ログインして続ける',
    email: 'メール',
    password: 'パスワード',
    login: 'ログイン',
    logging_in: 'ログイン中...',
    forgot_password: 'パスワードをお忘れですか？',
    reset_password: 'パスワードのリセット',
    send_recovery_link: 'コードを送信',
    enter_recovery_code: 'リカバリーコード',
    new_password: '新しいパスワード',
    update_password: 'パスワードを更新',
    code_sent: 'コードをメールで送信しました（例：123456）',
    phone_verification: '電話番号認証',
    verify_now: '今すぐ認証',
    verified: '認証済み',
    unverified: '未認証',
    send_code: 'コード送信',
    enter_code: 'コード入力',
    verify: '確認',
    phone_code_sent: '携帯にコードを送信しました（例：5555）',
    invalid_code: '無効なコード',
    success_verified: '認証成功！',
    no_account: 'アカウントがない？',
    sign_up: '新規登録',
    create_account: 'アカウント作成',
    choose_role: '役割を選択',
    how_will_use: 'どのように利用しますか？',
    traveler: '旅行者',
    traveler_desc: '旅行を計画。',
    guide: 'ガイド',
    guide_desc: 'ツアーを案内。',
    provider: 'プロバイダー',
    provider_desc: 'サービス管理。',
    already_account: '登録済み？',
    full_name: '氏名',
    phone: '電話番号',
    creating_account: '作成中...',
    feed: 'フィード',
    guides: 'ガイド',
    providers: 'サービス',
    profile: 'プロフィール',
    search_placeholder: '検索...',
    no_results: '結果なし。',
    no_posts: '投稿なし。',
    create_post: '投稿作成',
    share_experience: '体験を共有...',
    post: '投稿',
    posting: '投稿中...',
    cancel: 'キャンセル',
    photo_video: '写真/動画',
    promote_service: 'サービス宣伝',
    info: '情報',
    my_bookings: '予約一覧',
    edit: '編集',
    save_changes: '保存',
    location: '場所',
    experience: '経験',
    visited_places: '訪れた場所',
    service_desc: 'サービス説明',
    public: '公開？',
    logout: 'ログアウト',
    verification: '本人確認',
    languages_spoken: '対応言語',
    guiding_locations: 'ガイド場所',
    provider_category: 'カテゴリー',
    operating_hours: '営業時間',
    website: 'サイト',
    amenities: '設備',
    cat_tour_agency: '旅行代理店',
    cat_resort: 'リゾート/キャンプ',
    cat_rental: 'レンタル',
    cat_restaurant: 'レストラン/ショップ',
    cat_transport: '交通機関',
    cat_other: 'その他',
    am_wifi: 'WiFi',
    am_parking: '駐車場',
    am_restaurant: 'レストラン',
    am_shower: 'シャワー',
    am_pool: 'プール',
    am_breakfast: '朝食',
    am_gear: 'キャンプ用品',
    am_guide: 'ガイド付き',
    verify_title: 'アカウント認証',
    verify_desc: '書類を提出してください。',
    id_card: '身分証/パスポート',
    cert_license: '証明書/許可証',
    verify_hint_tour: '旅行業許可証をアップロードしてください。',
    verify_hint_resort: '土地許可証をアップロードしてください。',
    verify_hint_rental: '事業登録証をアップロードしてください。',
    verify_hint_food: '衛生許可証をアップロードしてください。',
    verify_hint_generic: '公式書類をアップロードしてください。',
    upload_doc: 'アップロード',
    submit_verify: '提出',
    verify_status: 'ステータス',
    status_pending: '保留中',
    status_approved: '承認済み',
    status_rejected: '却下',
    language_exams: '語学試験',
    exam_desc: '試験を受けてください。（10問、10分）',
    take_exam: '受験する',
    score: 'スコア',
    passed: '合格',
    failed: '不合格',
    start_exam: '開始',
    time_remaining: '残り時間',
    submit_exam: '提出',
    book_now: '予約する',
    message: 'メッセージ',
    reviews: 'レビュー',
    submit_review: '送信',
    select_date: '日付選択',
    guests: '人数',
    payment_method: '支払方法',
    total: '合計',
    pay_book: '支払い',
    processing: '処理中...',
    online: 'オンライン',
    loading: '読み込み中...',
    find_locals: '地元ガイドを探す。',
    resorts_camps: 'リゾートとサービス。',
    no_registered: '登録なし。',
    map_view: '地図',
    list_view: 'リスト',
    view_profile: 'プロフィールを見る',
    translator: '翻訳機',
    translate_desc: 'AI翻訳',
    type_to_translate: '入力...',
    listening: '聞いています...',
    tap_to_speak: '話す',
    translating: '翻訳中...',
    account_pending_action: '承認待ちです。',
    provider_pending_action: '承認待ちユーザーです。',
    ai_powered: 'AI搭載',
    copied: 'コピーしました！',
    dashboard: 'ダッシュボード',
    saved: '保存済み',
    add_post: '投稿を追加',
    followers: 'フォロワー',
    following: 'フォロー中',
    travel_gallery: '旅行ギャラリー',
    my_services: '私のサービス',
    my_travels: '私の旅行',
    total_earnings: '総収益',
    total_bookings: '総予約数',
    bookings_list: '予約リスト',
    no_active_bookings: 'アクティブな予約はありません。',
    status_confirmed: '確認済み',
    status_cancelled: 'キャンセル済み',
    where_to_travel: 'どこへ旅行しますか？',
    days: '日数',
    budget_economic: 'エコノミー',
    budget_standard: '標準',
    budget_luxury: '高級',
    generate_plan: 'プラン作成',
    itinerary: '旅程',
    ai_planner: 'AIプランナー',
    status_passed: '合格',
    status_failed: '不合格',
    messages: 'メッセージ',
    no_messages: 'メッセージはまだありません。',
    start_conversation_hint: 'ユーザープロフィールから会話を開始してください。',
    confirm_delete_msg: 'このメッセージを削除しますか？',
    confirm_delete_chat: 'チャット履歴をすべて削除しますか？元に戻すことはできません。',
    send_failed: '送信に失敗しました',
    backend_error: 'サーバーエラー',
    mic_error: 'マイクへのアクセスが拒否されました',
    upload_failed: 'アップロードに失敗しました',
    you_blocked_user: 'このユーザーをブロックしました',
    user_blocked_you: 'このユーザーによってブロックされています',
    message_placeholder: 'メッセージ...',
    delete_chat: 'チャットを削除',
    delete: '削除',
    voice_call: '音声通話',
    video_call: 'ビデオ通話',
    connecting: '接続中...',
    video_calling: 'ビデオ通話中...',
    voice_calling: '音声通話中...',
    mute: 'ミュート',
    mic: 'マイク',
    camera: 'カメラ',
    speaker: 'スピーカー',
    end_call: '終了',
    notifications: '通知',
    no_notifications: '通知はありません',
    notif_like: 'があなたの投稿に「いいね」しました。',
    notif_review: 'がレビューを書きました。',
    notif_approved: 'アカウントが承認されました！すべての機能が利用可能です。',
    notif_rejected: 'アカウントが拒否されました。更新して再送信してください。',
    notif_follow: 'があなたをフォローしました。',
    notif_call: 'があなたに電話をかけています...',
    notif_comment: 'があなたの投稿にコメントしました。',
    share_travel_note: '旅行のメモや経験を共有...',
    is_service: 'サービス',
    service_name: 'サービス名',
    price: '価格',
    capacity: '定員',
    incoming_video_call: 'ビデオ通話が着信しています...',
    incoming_voice_call: '音声通話が着信しています...',
    accept: '応答',
    decline: '拒否',
    missed_video_call: '不在着信ビデオ通話',
    missed_voice_call: '不在着信音声通話',
    video_call_log: 'ビデオ通話',
    voice_call_log: '音声通話',
    online_status: 'オンライン',
    language_name: 'Japanese',
    // Landing page translations
    hero_badge: 'モンゴル最高の旅行プラットフォーム',
    hero_subtitle: 'プロのガイドを見つけ、ツアーを予約し、息をのむような目的地を発見する — すべてが1か所で。',
    stat_guides: 'ガイド',
    stat_travelers: '旅行者',
    stat_destinations: '目的地',
    stat_languages: '言語',
    get_started: '今すぐ始める',
    services_title: 'サービス',
    services_desc: 'VIP Travelプラットフォームで旅行のすべてのニーズを満たしましょう。',
    view_all_services: 'すべてのサービスを見る',
    all_services_title: 'すべてのサービス',
    all_services_desc: 'VIP Travelプラットフォームのすべてのサービス',
    // Service translations
    service_find_guide: 'ガイドを探す',
    service_find_guide_desc: '国内外のガイドを閲覧・比較し、評価とレビューを見て最適なガイドを選ぼう。',
    service_book_tour: 'ツアーを予約',
    service_book_tour_desc: 'ガイドと直接連絡してツアーを予約。QPay、SocialPayまたはカードで簡単に支払い。',
    service_interactive_map: 'インタラクティブマップ',
    service_interactive_map_desc: 'Mapbox搭載。インタラクティブマップでガイドとサービス提供者をリアルタイムで確認。',
    service_translator: '翻訳機能',
    service_translator_desc: '10言語に対応した組み込み翻訳でガイドと旅行者のシームレスなコミュニケーション。',
    service_chat_calls: 'チャットと通話',
    service_chat_calls_desc: 'Cloudflare Callsによる旅行者とガイド間のダイレクトメッセージとビデオ通話。',
    service_social_feed: 'ソーシャルフィード',
    service_social_feed_desc: '旅の思い出を共有し、写真やビデオを投稿し、レビューを残し、コミュニティに参加しよう。',
    service_provider_services: 'プロバイダーサービス',
    service_provider_services_desc: 'キャンプ場、スパ、交通、レストラン、レンタルサービスをすべて一か所で予約。',
    service_guide_verification: 'ガイド認証',
    service_guide_verification_desc: 'すべてのガイドが公式文書と証明書で認証済み。安全で信頼できる旅行が保証。',
    service_live_streaming: 'ライブストリーミング',
    service_live_streaming_desc: 'ガイドや観光地からのライブストリームを見て、冒険を事前にプレビュー。'
  },
  ko: {
    welcome_back: '환영합니다',
    login_subtitle: '로그인하여 계속',
    email: '이메일',
    password: '비밀번호',
    login: '로그인',
    logging_in: '로그인 중...',
    forgot_password: '비밀번호 찾기?',
    reset_password: '비밀번호 재설정',
    send_recovery_link: '코드 전송',
    enter_recovery_code: '복구 코드',
    new_password: '새 비밀번호',
    update_password: '비밀번호 업데이트',
    code_sent: '이메일로 코드 전송됨 (예: 123456)',
    phone_verification: '전화 인증',
    verify_now: '지금 인증',
    verified: '인증됨',
    unverified: '미인증',
    send_code: '코드 전송',
    enter_code: '코드 입력',
    verify: '확인',
    phone_code_sent: '휴대전화로 코드 전송됨 (예: 5555)',
    invalid_code: '유효하지 않은 코드',
    success_verified: '성공적으로 인증됨!',
    no_account: '계정이 없나요?',
    sign_up: '회원가입',
    create_account: '계정 생성',
    choose_role: '역할 선택',
    how_will_use: '어떻게 사용하시겠습니까?',
    traveler: '여행자',
    traveler_desc: '여행 계획.',
    guide: '가이드',
    guide_desc: '투어 안내.',
    provider: '제공자',
    provider_desc: '서비스 관리.',
    already_account: '이미 가입함?',
    full_name: '성명',
    phone: '전화번호',
    creating_account: '생성 중...',
    feed: '피드',
    guides: '가이드',
    providers: '서비스',
    profile: '프로필',
    search_placeholder: '검색...',
    no_results: '결과 없음.',
    no_posts: '게시물 없음.',
    create_post: '게시물 작성',
    share_experience: '경험 공유...',
    post: '게시',
    posting: '게시 중...',
    cancel: '취소',
    photo_video: '사진/영상',
    promote_service: '서비스 홍보',
    info: '정보',
    my_bookings: '예약 내역',
    edit: '수정',
    save_changes: '저장',
    location: '위치',
    experience: '경험',
    visited_places: '방문한 곳',
    service_desc: '서비스 설명',
    public: '공개?',
    logout: '로그아웃',
    verification: '인증',
    languages_spoken: '언어 능력',
    guiding_locations: '가이드 장소',
    provider_category: '카테고리',
    operating_hours: '영업 시간',
    website: '웹사이트',
    amenities: '편의 시설',
    cat_tour_agency: '여행사',
    cat_resort: '리조트/캠프',
    cat_rental: '렌탈',
    cat_restaurant: '식당/상점',
    cat_transport: '교통',
    cat_other: '기타',
    am_wifi: '와이파이',
    am_parking: '주차장',
    am_restaurant: '식당',
    am_shower: '샤워',
    am_pool: '수영장',
    am_breakfast: '조식',
    am_gear: '장비',
    am_guide: '가이드',
    verify_title: '계정 인증',
    verify_desc: '서류를 제출하세요.',
    id_card: '신분증/여권',
    cert_license: '자격증/허가증',
    verify_hint_tour: '여행업 면허를 업로드하세요.',
    verify_hint_resort: '토지 허가증을 업로드하세요.',
    verify_hint_rental: '사업자 등록증을 업로드하세요.',
    verify_hint_food: '위생 허가증을 업로드하세요.',
    verify_hint_generic: '공식 서류를 업로드하세요.',
    upload_doc: '업로드',
    submit_verify: '제출',
    verify_status: '상태',
    status_pending: '대기 중',
    status_approved: '승인됨',
    status_rejected: '거절됨',
    language_exams: '어학 시험',
    exam_desc: '시험을 치르세요. (10문제, 10분)',
    take_exam: '시험 보기',
    score: '점수',
    passed: '합격',
    failed: '불합격',
    start_exam: '시작',
    time_remaining: '시간',
    submit_exam: '제출',
    book_now: '예약하기',
    message: '메시지',
    reviews: '리뷰',
    submit_review: '제출',
    select_date: '날짜 선택',
    guests: '인원',
    payment_method: '결제 수단',
    total: '합계',
    pay_book: '결제',
    processing: '처리 중...',
    online: '온라인',
    loading: '로딩 중...',
    find_locals: '현지 가이드 찾기.',
    resorts_camps: '리조트 및 서비스.',
    no_registered: '등록 없음.',
    map_view: '지도',
    list_view: '목록',
    view_profile: '프로필 보기',
    translator: '번역기',
    translate_desc: 'AI 번역',
    type_to_translate: '입력...',
    listening: '듣는 중...',
    tap_to_speak: '말하기',
    translating: '번역 중...',
    account_pending_action: '승인 대기 중입니다.',
    provider_pending_action: '승인 대기 사용자입니다.',
    ai_powered: 'AI 기반',
    copied: '복사되었습니다!',
    dashboard: '대시보드',
    saved: '저장됨',
    add_post: '게시물 추가',
    followers: '팔로워',
    following: '팔로잉',
    travel_gallery: '여행 갤러리',
    my_services: '나의 서비스',
    my_travels: '나의 여행',
    total_earnings: '총 수익',
    total_bookings: '총 예약',
    bookings_list: '예약 목록',
    no_active_bookings: '활성 예약이 없습니다.',
    status_confirmed: '확인됨',
    status_cancelled: '취소됨',
    where_to_travel: '어디로 여행가세요?',
    days: '일수',
    budget_economic: '경제적',
    budget_standard: '표준',
    budget_luxury: '럭셔리',
    generate_plan: '계획 생성',
    itinerary: '일정',
    ai_planner: 'AI 플래너',
    status_passed: '합격',
    status_failed: '불합격',
    messages: '메시지',
    no_messages: '아직 메시지가 없습니다.',
    start_conversation_hint: '사용자 프로필에서 대화를 시작하세요.',
    confirm_delete_msg: '이 메시지를 삭제하시겠습니까?',
    confirm_delete_chat: '전체 채팅 기록을 삭제하시겠습니까? 되돌릴 수 없습니다.',
    send_failed: '전송 실패',
    backend_error: '서버 오류',
    mic_error: '마이크 액세스 거부됨',
    upload_failed: '업로드 실패',
    you_blocked_user: '이 사용자를 차단했습니다',
    user_blocked_you: '이 사용자에게 차단되었습니다',
    message_placeholder: '메시지...',
    delete_chat: '채팅 삭제',
    delete: '삭제',
    voice_call: '음성 통화',
    video_call: '영상 통화',
    connecting: '연결 중...',
    video_calling: '영상 통화 중...',
    voice_calling: '음성 통화 중...',
    mute: '음소거',
    mic: '마이크',
    camera: '카메라',
    speaker: '스피커',
    end_call: '종료',
    notifications: '알림',
    no_notifications: '알림 없음',
    notif_like: '님이 귀하의 게시물을 좋아합니다.',
    notif_review: '님이 리뷰를 남겼습니다.',
    notif_approved: '계정이 승인되었습니다! 모든 기능이 잠금 해제되었습니다.',
    notif_rejected: '계정이 거부되었습니다. 업데이트 후 다시 제출하세요.',
    notif_follow: '님이 팔로우하기 시작했습니다.',
    notif_call: '님이 전화 중입니다...',
    notif_comment: '님이 귀하의 게시물에 댓글을 남겼습니다.',
    share_travel_note: '여행 노트와 경험을 공유하세요...',
    is_service: '서비스',
    service_name: '서비스 이름',
    price: '가격',
    capacity: '수용 인원',
    incoming_video_call: '영상 통화가 오고 있습니다...',
    incoming_voice_call: '음성 통화가 오고 있습니다...',
    accept: '받기',
    decline: '거절',
    missed_video_call: '부재중 영상 통화',
    missed_voice_call: '부재중 음성 통화',
    video_call_log: '영상 통화',
    voice_call_log: '음성 통화',
    online_status: '온라인',
    language_name: 'Korean',
    // Landing page translations
    hero_badge: '몽골 최고의 여행 플랫폼',
    hero_subtitle: '전문 가이드 찾기, 투어 예약, 놀라운 여행지 발견 — 모두 한 곳에서.',
    stat_guides: '가이드',
    stat_travelers: '여행자',
    stat_destinations: '여행지',
    stat_languages: '언어',
    get_started: '지금 시작하기',
    services_title: '서비스',
    services_desc: 'VIP Travel 플랫폼을 통해 모든 여행 필요를 충족하세요.',
    view_all_services: '모든 서비스 보기',
    all_services_title: '모든 서비스',
    all_services_desc: 'VIP Travel 플랫폼의 모든 서비스',
    // Service translations
    service_find_guide: '가이드 찾기',
    service_find_guide_desc: '국내외 가이드를 탐색하고 비교하여 평점과 리뷰를 통해 최적의 가이드를 선택하세요.',
    service_book_tour: '투어 예약',
    service_book_tour_desc: '가이드와 직접 연락하여 투어를 예약하세요. QPay, SocialPay 또는 카드로 간편 결제.',
    service_interactive_map: '인터랙티브 지도',
    service_interactive_map_desc: 'Mapbox 기반. 인터랙티브 지도에서 가이드와 서비스 제공자를 실시간으로 확인하세요.',
    service_translator: '번역기',
    service_translator_desc: '10개 언어를 지원하는 내장 번역으로 가이드와 여행자 간 원활한 소통.',
    service_chat_calls: '채팅 & 통화',
    service_chat_calls_desc: 'Cloudflare Calls를 통한 여행자와 가이드 간 직접 메시지 및 화상 통화.',
    service_social_feed: '소셜 피드',
    service_social_feed_desc: '여행 순간을 공유하고, 사진과 동영상을 게시하고, 리뷰를 남기고, 커뮤니티에 참여하세요.',
    service_provider_services: '서비스 제공업체',
    service_provider_services_desc: '캠프, 스파, 교통, 레스토랑, 렌탈 서비스를 한 곳에서 예약하세요.',
    service_guide_verification: '가이드 인증',
    service_guide_verification_desc: '모든 가이드는 공식 문서와 인증서로 검증되었습니다.',
    service_live_streaming: '라이브 스트리밍',
    service_live_streaming_desc: '가이드와 여행지에서 라이브 스트림을 시청하여 모험을 미리 확인하세요.'
  },
  de: {
    welcome_back: 'Willkommen zurück',
    login_subtitle: 'Einloggen um fortzufahren',
    email: 'E-Mail',
    password: 'Passwort',
    login: 'Anmelden',
    logging_in: 'Anmeldung...',
    forgot_password: 'Passwort vergessen?',
    reset_password: 'Passwort zurücksetzen',
    send_recovery_link: 'Code senden',
    enter_recovery_code: 'Wiederherstellungscode',
    new_password: 'Neues Passwort',
    update_password: 'Passwort aktualisieren',
    code_sent: 'Code gesendet (Bsp: 123456)',
    phone_verification: 'Telefonverifizierung',
    verify_now: 'Verifizieren',
    verified: 'Verifiziert',
    unverified: 'Nicht verifiziert',
    send_code: 'Code senden',
    enter_code: 'Code eingeben',
    verify: 'Prüfen',
    phone_code_sent: 'Code an Handy gesendet (Bsp: 5555)',
    invalid_code: 'Ungültiger Code',
    success_verified: 'Erfolgreich!',
    no_account: 'Kein Konto?',
    sign_up: 'Registrieren',
    create_account: 'Konto erstellen',
    choose_role: 'Rolle wählen',
    how_will_use: 'Nutzung?',
    traveler: 'Reisender',
    traveler_desc: 'Reisen planen.',
    guide: 'Führer',
    guide_desc: 'Touren leiten.',
    provider: 'Anbieter',
    provider_desc: 'Dienste verwalten.',
    already_account: 'Bereits registriert?',
    full_name: 'Name',
    phone: 'Telefon',
    creating_account: 'Erstelle...',
    feed: 'Feed',
    guides: 'Führer',
    providers: 'Anbieter',
    profile: 'Profil',
    search_placeholder: 'Suchen...',
    no_results: 'Keine Ergebnisse.',
    no_posts: 'Keine Beiträge.',
    create_post: 'Beitrag erstellen',
    share_experience: 'Teilen...',
    post: 'Posten',
    posting: 'Poste...',
    cancel: 'Abbrechen',
    photo_video: 'Foto/Video',
    promote_service: 'Bewerben',
    info: 'Info',
    my_bookings: 'Buchungen',
    edit: 'Bearbeiten',
    save_changes: 'Speichern',
    location: 'Ort',
    experience: 'Erfahrung',
    visited_places: 'Besuchte Orte',
    service_desc: 'Beschreibung',
    public: 'Öffentlich?',
    logout: 'Abmelden',
    verification: 'Verifizierung',
    languages_spoken: 'Sprachen',
    guiding_locations: 'Orte',
    provider_category: 'Kategorie',
    operating_hours: 'Öffnungszeiten',
    website: 'Webseite',
    amenities: 'Ausstattung',
    cat_tour_agency: 'Reisebüro',
    cat_resort: 'Resort',
    cat_rental: 'Verleih',
    cat_restaurant: 'Restaurant',
    cat_transport: 'Transport',
    cat_other: 'Andere',
    am_wifi: 'WiFi',
    am_parking: 'Parkplatz',
    am_restaurant: 'Restaurant',
    am_shower: 'Dusche',
    am_pool: 'Pool',
    am_breakfast: 'Frühstück',
    am_gear: 'Ausrüstung',
    am_guide: 'Führer',
    verify_title: 'Verifizierung',
    verify_desc: 'Dokumente einreichen.',
    id_card: 'Ausweis',
    cert_license: 'Lizenz',
    verify_hint_tour: 'Lizenz hochladen.',
    verify_hint_resort: 'Genehmigung hochladen.',
    verify_hint_rental: 'Registrierung hochladen.',
    verify_hint_food: 'Genehmigung hochladen.',
    verify_hint_generic: 'Dokumente hochladen.',
    upload_doc: 'Hochladen',
    submit_verify: 'Senden',
    verify_status: 'Status',
    status_pending: 'Ausstehend',
    status_approved: 'Genehmigt',
    status_rejected: 'Abgelehnt',
    language_exams: 'Sprachtests',
    exam_desc: 'Test machen. (10 Fragen, 10 Min)',
    take_exam: 'Test starten',
    score: 'Punkte',
    passed: 'Bestanden',
    failed: 'Nicht bestanden',
    start_exam: 'Start',
    time_remaining: 'Zeit',
    submit_exam: 'Senden',
    book_now: 'Buchen',
    message: 'Nachricht',
    reviews: 'Bewertungen',
    submit_review: 'Senden',
    select_date: 'Datum',
    guests: 'Gäste',
    payment_method: 'Zahlung',
    total: 'Gesamt',
    pay_book: 'Bezahlen',
    processing: 'Verarbeitung...',
    online: 'Online',
    loading: 'Laden...',
    find_locals: 'Einheimische finden.',
    resorts_camps: 'Resorts & Dienste.',
    no_registered: 'Keine Einträge.',
    map_view: 'Karte',
    list_view: 'Liste',
    view_profile: 'Profil',
    translator: 'Übersetzer',
    translate_desc: 'AI-Übersetzung',
    type_to_translate: 'Tippen...',
    listening: 'Höre...',
    tap_to_speak: 'Sprechen',
    translating: 'Übersetze...',
    account_pending_action: 'Konto ausstehend.',
    provider_pending_action: 'Anbieter ausstehend.',
    ai_powered: 'AI-betrieben',
    copied: 'Kopiert!',
    dashboard: 'Dashboard',
    saved: 'Gespeichert',
    add_post: 'Beitrag erstellen',
    followers: 'Follower',
    following: 'Folgt',
    travel_gallery: 'Reisegalerie',
    my_services: 'Meine Dienste',
    my_travels: 'Meine Reisen',
    total_earnings: 'Gesamteinnahmen',
    total_bookings: 'Gesamtbuchungen',
    bookings_list: 'Buchungsliste',
    no_active_bookings: 'Keine aktiven Buchungen.',
    status_confirmed: 'Bestätigt',
    status_cancelled: 'Storniert',
    where_to_travel: 'Wohin reisen?',
    days: 'Tage',
    budget_economic: 'Günstig',
    budget_standard: 'Standard',
    budget_luxury: 'Luxus',
    generate_plan: 'Plan erstellen',
    itinerary: 'Reiseroute',
    ai_planner: 'AI Planer',
    status_passed: 'Bestanden',
    status_failed: 'Nicht bestanden',
    messages: 'Nachrichten',
    no_messages: 'Noch keine Nachrichten.',
    start_conversation_hint: 'Starten Sie eine Konversation über das Benutzerprofil.',
    confirm_delete_msg: 'Diese Nachricht löschen?',
    confirm_delete_chat: 'Gesamten Chatverlauf löschen? Dies kann nicht rückgängig gemacht werden.',
    send_failed: 'Senden fehlgeschlagen',
    backend_error: 'Serverfehler',
    mic_error: 'Mikrofonzugriff verweigert',
    upload_failed: 'Upload fehlgeschlagen',
    you_blocked_user: 'Sie haben diesen Benutzer blockiert',
    user_blocked_you: 'Sie wurden von diesem Benutzer blockiert',
    message_placeholder: 'Nachricht...',
    delete_chat: 'Chat löschen',
    delete: 'Löschen',
    voice_call: 'Sprachanruf',
    video_call: 'Videoanruf',
    connecting: 'Verbinden...',
    video_calling: 'Videoanruf...',
    voice_calling: 'Sprachanruf...',
    mute: 'Stumm',
    mic: 'Mikro',
    camera: 'Kamera',
    speaker: 'Lautsprecher',
    end_call: 'Beenden',
    notifications: 'Benachrichtigungen',
    no_notifications: 'Keine Benachrichtigungen',
    notif_like: 'gefällt dein Beitrag.',
    notif_review: 'hat eine Bewertung abgegeben.',
    notif_approved: 'hat dein Konto genehmigt! Alle Funktionen freigeschaltet.',
    notif_rejected: 'hat dein Konto abgelehnt. Bitte aktualisieren und erneut senden.',
    notif_follow: 'folgt dir jetzt.',
    notif_call: 'ruft dich an...',
    notif_comment: 'hat deinen Beitrag kommentiert.',
    share_travel_note: 'Teilen Sie Ihre Reisenotizen und Erfahrungen...',
    is_service: 'Dienstleistung',
    service_name: 'Name der Dienstleistung',
    price: 'Preis',
    capacity: 'Kapazität',
    incoming_video_call: 'Eingehender Videoanruf...',
    incoming_voice_call: 'Eingehender Sprachanruf...',
    accept: 'Annehmen',
    decline: 'Ablehnen',
    missed_video_call: 'Verpasster Videoanruf',
    missed_voice_call: 'Verpasster Sprachanruf',
    video_call_log: 'Videoanruf',
    voice_call_log: 'Sprachanruf',
    online_status: 'Online',
    language_name: 'German',
    // Landing page translations
    hero_badge: 'Mongoleis führende Reiseplattform',
    hero_subtitle: 'Finden Sie professionelle Guides, buchen Sie Touren, entdecken Sie atemberaubende Reiseziele — alles an einem Ort.',
    stat_guides: 'Reiseführer',
    stat_travelers: 'Reisende',
    stat_destinations: 'Reiseziele',
    stat_languages: 'Sprachen',
    get_started: 'Jetzt starten',
    services_title: 'Dienstleistungen',
    services_desc: 'Erfüllen Sie alle Ihre Reisebedürfnisse über die VIP Travel Plattform.',
    view_all_services: 'Alle Dienste anzeigen',
    all_services_title: 'Alle Dienste',
    all_services_desc: 'Alle Dienste der VIP Travel Plattform',
    // Service translations
    service_find_guide: 'Guide finden',
    service_find_guide_desc: 'Vergleichen Sie in- und ausländische Guides und wählen Sie den Richtigen anhand von Bewertungen.',
    service_book_tour: 'Tour buchen',
    service_book_tour_desc: 'Kontaktieren Sie Guides direkt für Buchungen. Einfache Zahlung via QPay, SocialPay oder Karte.',
    service_interactive_map: 'Interaktive Karte',
    service_interactive_map_desc: 'Mapbox-gestützt. Sehen Sie Guides und Anbieter in Echtzeit auf einer interaktiven Karte.',
    service_translator: 'Übersetzer',
    service_translator_desc: 'Eingebaute Übersetzung für 10 Sprachen für nahtlose Kommunikation.',
    service_chat_calls: 'Chat & Anrufe',
    service_chat_calls_desc: 'Direktnachrichten und Videoanrufe via Cloudflare Calls.',
    service_social_feed: 'Social Feed',
    service_social_feed_desc: 'Teilen Sie Reisemomente, posten Sie Fotos und Videos, hinterlassen Sie Bewertungen.',
    service_provider_services: 'Anbieterservices',
    service_provider_services_desc: 'Buchen Sie Camps, Spas, Transport, Restaurants und Mietservices an einem Ort.',
    service_guide_verification: 'Guide-Verifizierung',
    service_guide_verification_desc: 'Alle Guides durch offizielle Dokumente und Zertifikate verifiziert.',
    service_live_streaming: 'Livestreaming',
    service_live_streaming_desc: 'Sehen Sie Livestreams von Guides und Orten für eine Vorschau auf Ihr Abenteuer.'
  },
  fr: {
    welcome_back: 'Bon retour',
    login_subtitle: 'Se connecter pour continuer',
    email: 'E-mail',
    password: 'Mot de passe',
    login: 'Connexion',
    logging_in: 'Connexion...',
    forgot_password: 'Mot de passe oublié ?',
    reset_password: 'Réinitialiser',
    send_recovery_link: 'Envoyer code',
    enter_recovery_code: 'Code récup.',
    new_password: 'Nouveau mot de passe',
    update_password: 'Mettre à jour',
    code_sent: 'Code envoyé (Ex: 123456)',
    phone_verification: 'Vérif. téléphone',
    verify_now: 'Vérifier',
    verified: 'Vérifié',
    unverified: 'Non vérifié',
    send_code: 'Envoyer code',
    enter_code: 'Entrer code',
    verify: 'Vérifier',
    phone_code_sent: 'Code envoyé au mobile (Ex: 5555)',
    invalid_code: 'Code invalide',
    success_verified: 'Succès !',
    no_account: 'Pas de compte ?',
    sign_up: 'S\'inscrire',
    create_account: 'Créer compte',
    choose_role: 'Choisir rôle',
    how_will_use: 'Usage ?',
    traveler: 'Voyageur',
    traveler_desc: 'Planifier.',
    guide: 'Guide',
    guide_desc: 'Guider.',
    provider: 'Fournisseur',
    provider_desc: 'Gérer.',
    already_account: 'Déjà inscrit ?',
    full_name: 'Nom',
    phone: 'Téléphone',
    creating_account: 'Création...',
    feed: 'Fil',
    guides: 'Guides',
    providers: 'Services',
    profile: 'Profil',
    search_placeholder: 'Chercher...',
    no_results: 'Aucun résultat.',
    no_posts: 'Aucun post.',
    create_post: 'Créer post',
    share_experience: 'Partager...',
    post: 'Publier',
    posting: 'Publication...',
    cancel: 'Annuler',
    photo_video: 'Photo/Vidéo',
    promote_service: 'Promouvoir',
    info: 'Info',
    my_bookings: 'Réservations',
    edit: 'Modifier',
    save_changes: 'Enregistrer',
    location: 'Lieu',
    experience: 'Expérience',
    visited_places: 'Lieux visités',
    service_desc: 'Description',
    public: 'Public ?',
    logout: 'Déconnexion',
    verification: 'Vérification',
    languages_spoken: 'Langues',
    guiding_locations: 'Lieux',
    provider_category: 'Catégorie',
    operating_hours: 'Horaires',
    website: 'Site',
    amenities: 'Équipements',
    cat_tour_agency: 'Agence',
    cat_resort: 'Resort',
    cat_rental: 'Location',
    cat_restaurant: 'Resto',
    cat_transport: 'Transport',
    cat_other: 'Autre',
    am_wifi: 'WiFi',
    am_parking: 'Parking',
    am_restaurant: 'Resto',
    am_shower: 'Douche',
    am_pool: 'Piscine',
    am_breakfast: 'Petit-déj',
    am_gear: 'Matériel',
    am_guide: 'Guide',
    verify_title: 'Vérification',
    verify_desc: 'Soumettre documents.',
    id_card: 'Identité',
    cert_license: 'Licence',
    verify_hint_tour: 'Licence agence.',
    verify_hint_resort: 'Permis terrain.',
    verify_hint_rental: 'Enreg. commerce.',
    verify_hint_food: 'Permis hygiène.',
    verify_hint_generic: 'Documents officiels.',
    upload_doc: 'Charger',
    submit_verify: 'Soumettre',
    verify_status: 'Statut',
    status_pending: 'En attente',
    status_approved: 'Approuvé',
    status_rejected: 'Rejeté',
    language_exams: 'Examens',
    exam_desc: 'Passer test. (10 questions, 10 min)',
    take_exam: 'Passer',
    score: 'Score',
    passed: 'Réussi',
    failed: 'Échoué',
    start_exam: 'Début',
    time_remaining: 'Temps',
    submit_exam: 'Finir',
    book_now: 'Réserver',
    message: 'Message',
    reviews: 'Avis',
    submit_review: 'Envoyer',
    select_date: 'Date',
    guests: 'Invités',
    payment_method: 'Paiement',
    total: 'Total',
    pay_book: 'Payer',
    processing: 'Traitement...',
    online: 'En ligne',
    loading: 'Chargement...',
    find_locals: 'Locaux.',
    resorts_camps: 'Services.',
    no_registered: 'Personne.',
    map_view: 'Carte',
    list_view: 'Liste',
    view_profile: 'Profil',
    translator: 'Traducteur',
    translate_desc: 'Traduction AI',
    type_to_translate: 'Taper...',
    listening: 'Écoute...',
    tap_to_speak: 'Parler',
    translating: 'Traduction...',
    account_pending_action: 'Compte en attente.',
    provider_pending_action: 'Utilisateur en attente.',
    ai_powered: 'Alimenté par IA',
    copied: 'Copié !',
    dashboard: 'Tableau de bord',
    saved: 'Enregistré',
    add_post: 'Ajouter un post',
    followers: 'Abonnés',
    following: 'Abonnements',
    travel_gallery: 'Galerie de voyage',
    my_services: 'Mes services',
    my_travels: 'Mes voyages',
    total_earnings: 'Gains totaux',
    total_bookings: 'Réservations totales',
    bookings_list: 'Liste des réservations',
    no_active_bookings: 'Aucune réservation active.',
    status_confirmed: 'Confirmé',
    status_cancelled: 'Annulé',
    where_to_travel: 'Où voyager ?',
    days: 'Jours',
    budget_economic: 'Économique',
    budget_standard: 'Standard',
    budget_luxury: 'Luxe',
    generate_plan: 'Générer un plan',
    itinerary: 'Itinéraire',
    ai_planner: 'Planificateur AI',
    status_passed: 'Réussi',
    status_failed: 'Échoué',
    messages: 'Messages',
    no_messages: 'Pas encore de messages.',
    start_conversation_hint: 'Démarrez une conversation depuis le profil d\'un utilisateur.',
    confirm_delete_msg: 'Supprimer ce message ?',
    confirm_delete_chat: 'Supprimer tout l\'historique de chat ? Ceci est irréversible.',
    send_failed: 'Échec de l\'envoi',
    backend_error: 'Erreur serveur',
    mic_error: 'Accès au microphone refusé',
    upload_failed: 'Échec du téléchargement',
    you_blocked_user: 'Vous avez bloqué cet utilisateur',
    user_blocked_you: 'Vous avez été bloqué par cet utilisateur',
    message_placeholder: 'Message...',
    delete_chat: 'Supprimer le chat',
    delete: 'Supprimer',
    voice_call: 'Appel vocal',
    video_call: 'Appel vidéo',
    connecting: 'Connexion...',
    video_calling: 'Appel vidéo...',
    voice_calling: 'Appel vocal...',
    mute: 'Muet',
    mic: 'Micro',
    camera: 'Caméra',
    speaker: 'Haut-parleur',
    end_call: 'Terminer',
    notifications: 'Notifications',
    no_notifications: 'Aucune notification',
    notif_like: 'a aimé votre publication.',
    notif_review: 'vous a donné un avis.',
    notif_approved: 'a approuvé votre compte ! Toutes les fonctionnalités débloquées.',
    notif_rejected: 'a rejeté votre compte. Veuillez mettre à jour et soumettre à nouveau.',
    notif_follow: 'a commencé à vous suivre.',
    notif_call: 'vous appelle...',
    notif_comment: 'a commenté votre publication.',
    share_travel_note: 'Partagez vos notes de voyage et votre expérience...',
    is_service: 'Service',
    service_name: 'Nom du service',
    price: 'Prix',
    capacity: 'Capacité',
    incoming_video_call: 'Appel vidéo entrant...',
    incoming_voice_call: 'Appel vocal entrant...',
    accept: 'Accepter',
    decline: 'Refuser',
    missed_video_call: 'Appel vidéo manqué',
    missed_voice_call: 'Appel vocal manqué',
    video_call_log: 'Appel vidéo',
    voice_call_log: 'Appel vocal',
    online_status: 'En ligne',
    language_name: 'French',
    // Landing page translations
    hero_badge: 'La meilleure plateforme de voyage de Mongolie',
    hero_subtitle: 'Trouvez des guides professionnels, réservez des circuits, découvrez des destinations époustouflantes — tout en un seul endroit.',
    stat_guides: 'Guides',
    stat_travelers: 'Voyageurs',
    stat_destinations: 'Destinations',
    stat_languages: 'Langues',
    get_started: 'Commencer maintenant',
    services_title: 'Services',
    services_desc: 'Répondez à tous vos besoins de voyage via la plateforme VIP Travel.',
    view_all_services: 'Voir tous les services',
    all_services_title: 'Tous les services',
    all_services_desc: 'Tous les services de la plateforme VIP Travel',
    // Service translations
    service_find_guide: 'Trouver un guide',
    service_find_guide_desc: 'Parcourez et comparez les guides locaux et internationaux pour trouver votre guide idéal.',
    service_book_tour: 'Réserver un circuit',
    service_book_tour_desc: 'Contactez directement les guides pour réserver. Paiement facile via QPay, SocialPay ou carte.',
    service_interactive_map: 'Carte interactive',
    service_interactive_map_desc: 'Propulsé par Mapbox. Voyez les guides et prestataires en temps réel sur une carte interactive.',
    service_translator: 'Traducteur',
    service_translator_desc: 'Traduction intégrée supportant 10 langues pour une communication fluide.',
    service_chat_calls: 'Chat & appels',
    service_chat_calls_desc: 'Messages directs et appels vidéo entre voyageurs et guides via Cloudflare Calls.',
    service_social_feed: 'Fil social',
    service_social_feed_desc: 'Partagez vos moments de voyage, publiez photos et vidéos, laissez des avis.',
    service_provider_services: 'Services prestataires',
    service_provider_services_desc: 'Réservez campings, spas, transport, restaurants et services de location en un seul endroit.',
    service_guide_verification: 'Vérification des guides',
    service_guide_verification_desc: 'Tous les guides vérifiés avec des documents officiels et certificats.',
    service_live_streaming: 'Diffusion en direct',
    service_live_streaming_desc: 'Regardez des diffusions en direct de guides et destinations pour prévisualiser votre aventure.'
  },
  es: {
    welcome_back: 'Bienvenido',
    login_subtitle: 'Iniciar sesión para continuar',
    email: 'Correo',
    password: 'Clave',
    login: 'Entrar',
    logging_in: 'Entrando...',
    forgot_password: '¿Olvidó clave?',
    reset_password: 'Restablecer',
    send_recovery_link: 'Enviar código',
    enter_recovery_code: 'Código recup.',
    new_password: 'Nueva clave',
    update_password: 'Actualizar',
    code_sent: 'Código enviado (Ej: 123456)',
    phone_verification: 'Verif. teléfono',
    verify_now: 'Verificar',
    verified: 'Verificado',
    unverified: 'No verificado',
    send_code: 'Enviar código',
    enter_code: 'Ingresar código',
    verify: 'Verificar',
    phone_code_sent: 'Código al móvil (Ej: 5555)',
    invalid_code: 'Código inválido',
    success_verified: '¡Éxito!',
    no_account: '¿Sin cuenta?',
    sign_up: 'Registrarse',
    create_account: 'Crear cuenta',
    choose_role: 'Rol',
    how_will_use: '¿Uso?',
    traveler: 'Viajero',
    traveler_desc: 'Planear.',
    guide: 'Guía',
    guide_desc: 'Guiar.',
    provider: 'Proveedor',
    provider_desc: 'Gestionar.',
    already_account: '¿Registrado?',
    full_name: 'Nombre',
    phone: 'Teléfono',
    creating_account: 'Creando...',
    feed: 'Inicio',
    guides: 'Guías',
    providers: 'Servicios',
    profile: 'Perfil',
    search_placeholder: 'Buscar...',
    no_results: 'Sin resultados.',
    no_posts: 'Sin posts.',
    create_post: 'Crear post',
    share_experience: 'Compartir...',
    post: 'Publicar',
    posting: 'Publicando...',
    cancel: 'Cancelar',
    photo_video: 'Foto/Video',
    promote_service: 'Promover',
    info: 'Info',
    my_bookings: 'Reservas',
    edit: 'Editar',
    save_changes: 'Guardar',
    location: 'Ubicación',
    experience: 'Experiencia',
    visited_places: 'Lugares',
    service_desc: 'Descripción',
    public: '¿Público?',
    logout: 'Salir',
    verification: 'Verificación',
    languages_spoken: 'Idiomas',
    guiding_locations: 'Lugares',
    provider_category: 'Categoría',
    operating_hours: 'Horarios',
    website: 'Web',
    amenities: 'Servicios',
    cat_tour_agency: 'Agencia',
    cat_resort: 'Resort',
    cat_rental: 'Renta',
    cat_restaurant: 'Restaurante',
    cat_transport: 'Transporte',
    cat_other: 'Otro',
    am_wifi: 'WiFi',
    am_parking: 'Parking',
    am_restaurant: 'Restaurante',
    am_shower: 'Ducha',
    am_pool: 'Piscina',
    am_breakfast: 'Desayuno',
    am_gear: 'Equipo',
    am_guide: 'Guía',
    verify_title: 'Verificación',
    verify_desc: 'Enviar docs.',
    id_card: 'DNI',
    cert_license: 'Licencia',
    verify_hint_tour: 'Licencia operador.',
    verify_hint_resort: 'Permiso suelo.',
    verify_hint_rental: 'Registro.',
    verify_hint_food: 'Permiso salud.',
    verify_hint_generic: 'Docs oficiales.',
    upload_doc: 'Cargar',
    submit_verify: 'Enviar',
    verify_status: 'Estado',
    status_pending: 'Pendiente',
    status_approved: 'Aprobado',
    status_rejected: 'Rechazado',
    language_exams: 'Exámenes',
    exam_desc: 'Tomar examen. (10 preg, 10 min)',
    take_exam: 'Empezar',
    score: 'Puntaje',
    passed: 'Aprobado',
    failed: 'Reprobado',
    start_exam: 'Inicio',
    time_remaining: 'Tiempo',
    submit_exam: 'Fin',
    book_now: 'Reservar',
    message: 'Mensaje',
    reviews: 'Reseñas',
    submit_review: 'Enviar',
    select_date: 'Fecha',
    guests: 'Huéspedes',
    payment_method: 'Pago',
    total: 'Total',
    pay_book: 'Pagar',
    processing: 'Procesando...',
    online: 'En línea',
    loading: 'Cargando...',
    find_locals: 'Locales.',
    resorts_camps: 'Servicios.',
    no_registered: 'Nadie.',
    map_view: 'Mapa',
    list_view: 'Lista',
    view_profile: 'Ver perfil',
    translator: 'Traductor',
    translate_desc: 'Traducción AI',
    type_to_translate: 'Escribir...',
    listening: 'Escuchando...',
    tap_to_speak: 'Hablar',
    translating: 'Traduciendo...',
    account_pending_action: 'Cuenta pendiente.',
    provider_pending_action: 'Usuario pendiente.',
    ai_powered: 'Impulsado por IA',
    copied: '¡Copiado!',
    dashboard: 'Panel',
    saved: 'Guardado',
    add_post: 'Publicar',
    followers: 'Seguidores',
    following: 'Siguiendo',
    travel_gallery: 'Galería de viajes',
    my_services: 'Mis servicios',
    my_travels: 'Mis viajes',
    total_earnings: 'Ganancias totales',
    total_bookings: 'Reservas totales',
    bookings_list: 'Lista de reservas',
    no_active_bookings: 'No hay reservas activas.',
    status_confirmed: 'Confirmado',
    status_cancelled: 'Cancelado',
    where_to_travel: '¿A dónde viajar?',
    days: 'Días',
    budget_economic: 'Económico',
    budget_standard: 'Estándar',
    budget_luxury: 'Lujo',
    generate_plan: 'Generar plan',
    itinerary: 'Itinerario',
    ai_planner: 'Planificador AI',
    status_passed: 'Aprobado',
    status_failed: 'Reprobado',
    messages: 'Mensajes',
    no_messages: 'Aún no hay mensajes.',
    start_conversation_hint: 'Inicia una conversación desde el perfil de un usuario.',
    confirm_delete_msg: '¿Eliminar este mensaje?',
    confirm_delete_chat: '¿Eliminar todo el historial de chat? Esto no se puede deshacer.',
    send_failed: 'Error al enviar',
    backend_error: 'Error del servidor',
    mic_error: 'Acceso al micrófono denegado',
    upload_failed: 'Error al cargar',
    you_blocked_user: 'Has bloqueado a este usuario',
    user_blocked_you: 'Has sido bloqueado por este usuario',
    message_placeholder: 'Mensaje...',
    delete_chat: 'Eliminar chat',
    delete: 'Eliminar',
    voice_call: 'Llamada de voz',
    video_call: 'Videollamada',
    connecting: 'Conectando...',
    video_calling: 'Videollamada...',
    voice_calling: 'Llamada de voz...',
    mute: 'Silencio',
    mic: 'Micrófono',
    camera: 'Cámara',
    speaker: 'Altavoz',
    end_call: 'Finalizar',
    notifications: 'Notificaciones',
    no_notifications: 'Sin notificaciones',
    notif_like: 'le gustó tu publicación.',
    notif_review: 'te dio una reseña.',
    notif_approved: 'aprobó tu cuenta. ¡Todas las funciones desbloqueadas!',
    notif_rejected: 'rechazó tu cuenta. Por favor actualiza y vuelve a enviar.',
    notif_follow: 'comenzó a seguirte.',
    notif_call: 'te está llamando...',
    notif_comment: 'comentó en tu publicación.',
    share_travel_note: 'Comparte tus notas de viaje y experiencia...',
    is_service: 'Servicio',
    service_name: 'Nombre del servicio',
    price: 'Precio',
    capacity: 'Capacidad',
    incoming_video_call: 'Llamada de video entrante...',
    incoming_voice_call: 'Llamada de voz entrante...',
    accept: 'Aceptar',
    decline: 'Rechazar',
    missed_video_call: 'Llamada de video perdida',
    missed_voice_call: 'Llamada de voz perdida',
    video_call_log: 'Llamada de video',
    voice_call_log: 'Llamada de voz',
    online_status: 'En línea',
    language_name: 'Spanish',
    // Landing page translations
    hero_badge: 'La mejor plataforma de viajes de Mongolia',
    hero_subtitle: 'Encuentra guías profesionales, reserva tours, descubre destinos impresionantes — todo en un solo lugar.',
    stat_guides: 'Guías',
    stat_travelers: 'Viajeros',
    stat_destinations: 'Destinos',
    stat_languages: 'Idiomas',
    get_started: 'Comenzar ahora',
    services_title: 'Servicios',
    services_desc: 'Satisface todas tus necesidades de viaje a través de la plataforma VIP Travel.',
    view_all_services: 'Ver todos los servicios',
    all_services_title: 'Todos los servicios',
    all_services_desc: 'Todos los servicios de la plataforma VIP Travel',
    // Service translations
    service_find_guide: 'Encontrar guía',
    service_find_guide_desc: 'Explora y compara guías locales e internacionales para encontrar tu guía ideal.',
    service_book_tour: 'Reservar tour',
    service_book_tour_desc: 'Contacta directamente con guías para reservar. Pago fácil via QPay, SocialPay o tarjeta.',
    service_interactive_map: 'Mapa interactivo',
    service_interactive_map_desc: 'Con tecnología Mapbox. Ve guías y proveedores en tiempo real.',
    service_translator: 'Traductor',
    service_translator_desc: 'Traducción integrada que soporta 10 idiomas para comunicación fluida.',
    service_chat_calls: 'Chat y llamadas',
    service_chat_calls_desc: 'Mensajes directos y videollamadas via Cloudflare Calls.',
    service_social_feed: 'Feed social',
    service_social_feed_desc: 'Comparte momentos de viaje, publica fotos y videos, deja reseñas.',
    service_provider_services: 'Servicios de proveedores',
    service_provider_services_desc: 'Reserva campamentos, spas, transporte, restaurantes y alquileres en un solo lugar.',
    service_guide_verification: 'Verificación de guías',
    service_guide_verification_desc: 'Todos los guías verificados con documentos oficiales y certificados.',
    service_live_streaming: 'Transmisión en vivo',
    service_live_streaming_desc: 'Mira transmisiones en vivo de guías y destinos para previsualizar tu aventura.'
  },
  it: {
    welcome_back: 'Bentornato',
    login_subtitle: 'Accedi per continuare',
    email: 'Email',
    password: 'Password',
    login: 'Accedi',
    logging_in: 'Accesso...',
    forgot_password: 'Password dimenticata?',
    reset_password: 'Reimposta',
    send_recovery_link: 'Invia codice',
    enter_recovery_code: 'Codice rec.',
    new_password: 'Nuova password',
    update_password: 'Aggiorna',
    code_sent: 'Codice inviato (Es: 123456)',
    phone_verification: 'Verif. telefono',
    verify_now: 'Verifica',
    verified: 'Verificato',
    unverified: 'Non verificato',
    send_code: 'Invia codice',
    enter_code: 'Inserisci codice',
    verify: 'Verifica',
    phone_code_sent: 'Codice inviato al cell (Es: 5555)',
    invalid_code: 'Codice non valido',
    success_verified: 'Successo!',
    no_account: 'No account?',
    sign_up: 'Iscriviti',
    create_account: 'Crea account',
    choose_role: 'Ruolo',
    how_will_use: 'Uso?',
    traveler: 'Viaggiatore',
    traveler_desc: 'Pianifica.',
    guide: 'Guida',
    guide_desc: 'Guida.',
    provider: 'Fornitore',
    provider_desc: 'Gestisci.',
    already_account: 'Già iscritto?',
    full_name: 'Nome',
    phone: 'Telefono',
    creating_account: 'Creazione...',
    feed: 'Feed',
    guides: 'Guide',
    providers: 'Servizi',
    profile: 'Profilo',
    search_placeholder: 'Cerca...',
    no_results: 'Nessun risultato.',
    no_posts: 'Nessun post.',
    create_post: 'Crea post',
    share_experience: 'Condividi...',
    post: 'Pubblica',
    posting: 'Pubblicazione...',
    cancel: 'Annulla',
    photo_video: 'Foto/Video',
    promote_service: 'Promuovi',
    info: 'Info',
    my_bookings: 'Prenotazioni',
    edit: 'Modifica',
    save_changes: 'Salva',
    location: 'Posizione',
    experience: 'Esperienza',
    visited_places: 'Luoghi',
    service_desc: 'Descrizione',
    public: 'Pubblico?',
    logout: 'Esci',
    verification: 'Verifica',
    languages_spoken: 'Lingue',
    guiding_locations: 'Luoghi',
    provider_category: 'Categoria',
    operating_hours: 'Orari',
    website: 'Sito',
    amenities: 'Servizi',
    cat_tour_agency: 'Agenzia',
    cat_resort: 'Resort',
    cat_rental: 'Noleggio',
    cat_restaurant: 'Ristorante',
    cat_transport: 'Trasporto',
    cat_other: 'Altro',
    am_wifi: 'WiFi',
    am_parking: 'Parcheggio',
    am_restaurant: 'Ristorante',
    am_shower: 'Doccia',
    am_pool: 'Piscina',
    am_breakfast: 'Colazione',
    am_gear: 'Attrezzatura',
    am_guide: 'Guida',
    verify_title: 'Verifica',
    verify_desc: 'Invia doc.',
    id_card: 'Identità',
    cert_license: 'Licenza',
    verify_hint_tour: 'Licenza agenzia.',
    verify_hint_resort: 'Permesso suolo.',
    verify_hint_rental: 'Registrazione.',
    verify_hint_food: 'Permesso salute.',
    verify_hint_generic: 'Doc ufficiali.',
    upload_doc: 'Carica',
    submit_verify: 'Invia',
    verify_status: 'Stato',
    status_pending: 'In attesa',
    status_approved: 'Approvato',
    status_rejected: 'Rifiutato',
    language_exams: 'Esami',
    exam_desc: 'Fai esame. (10 dom, 10 min)',
    take_exam: 'Inizia',
    score: 'Punteggio',
    passed: 'Superato',
    failed: 'Fallito',
    start_exam: 'Inizio',
    time_remaining: 'Tempo',
    submit_exam: 'Fine',
    book_now: 'Prenota',
    message: 'Messaggio',
    reviews: 'Recensioni',
    submit_review: 'Invia',
    select_date: 'Data',
    guests: 'Ospiti',
    payment_method: 'Pagamento',
    total: 'Totale',
    pay_book: 'Paga',
    processing: 'Elaborazione...',
    online: 'Online',
    loading: 'Caricamento...',
    find_locals: 'Locali.',
    resorts_camps: 'Servizi.',
    no_registered: 'Nessuno.',
    map_view: 'Mappa',
    list_view: 'Elenco',
    view_profile: 'Profilo',
    translator: 'Traduttore',
    translate_desc: 'Traduzione AI',
    type_to_translate: 'Scrivi...',
    listening: 'Ascolto...',
    tap_to_speak: 'Parla',
    translating: 'Traduzione...',
    account_pending_action: 'Account in sospeso.',
    provider_pending_action: 'Utente in sospeso.',
    ai_powered: 'Alimentato da AI',
    copied: 'Copiato!',
    dashboard: 'Cruscotto',
    saved: 'Salvato',
    add_post: 'Aggiungi post',
    followers: 'Follower',
    following: 'Seguiti',
    travel_gallery: 'Galleria viaggi',
    my_services: 'I miei servizi',
    my_travels: 'I miei viaggi',
    total_earnings: 'Guadagni totali',
    total_bookings: 'Prenotazioni totali',
    bookings_list: 'Elenco prenotazioni',
    no_active_bookings: 'Nessuna prenotazione attiva.',
    status_confirmed: 'Confermato',
    status_cancelled: 'Cancellato',
    where_to_travel: 'Dove viaggiare?',
    days: 'Giorni',
    budget_economic: 'Economico',
    budget_standard: 'Standard',
    budget_luxury: 'Lusso',
    generate_plan: 'Genera piano',
    itinerary: 'Itinerario',
    ai_planner: 'Pianificatore AI',
    status_passed: 'Superato',
    status_failed: 'Fallito',
    messages: 'Messaggi',
    no_messages: 'Nessun messaggio ancora.',
    start_conversation_hint: 'Inizia una conversazione dal profilo di un utente.',
    confirm_delete_msg: 'Eliminare questo messaggio?',
    confirm_delete_chat: 'Eliminare l\'intera cronologia chat? Non può essere annullato.',
    send_failed: 'Invio fallito',
    backend_error: 'Errore del server',
    mic_error: 'Accesso al microfono negato',
    upload_failed: 'Caricamento fallito',
    you_blocked_user: 'Hai bloccato questo utente',
    user_blocked_you: 'Sei stato bloccato da questo utente',
    message_placeholder: 'Messaggio...',
    delete_chat: 'Elimina chat',
    delete: 'Elimina',
    voice_call: 'Chiamata vocale',
    video_call: 'Videochiamata',
    connecting: 'Connessione...',
    video_calling: 'Videochiamata...',
    voice_calling: 'Chiamata vocale...',
    mute: 'Muto',
    mic: 'Microfono',
    camera: 'Telecamera',
    speaker: 'Altoparlante',
    end_call: 'Termina',
    notifications: 'Notifiche',
    no_notifications: 'Nessuna notifica',
    notif_like: 'ha messo mi piace al tuo post.',
    notif_review: 'ti ha lasciato una recensione.',
    notif_approved: 'ha approvato il tuo account! Tutte le funzioni sbloccate.',
    notif_rejected: 'ha rifiutato il tuo account. Aggiorna e invia di nuovo.',
    notif_follow: 'ha iniziato a seguirti.',
    notif_call: 'ti sta chiamando...',
    notif_comment: 'ha commentato il tuo post.',
    share_travel_note: 'Condividi i tuoi appunti di viaggio ed esperienza...',
    is_service: 'Servizio',
    service_name: 'Nome del servizio',
    price: 'Prezzo',
    capacity: 'Capacidad',
    incoming_video_call: 'Chiamata video in arrivo...',
    incoming_voice_call: 'Chiamata vocale in arrivo...',
    accept: 'Accetta',
    decline: 'Rifiuta',
    missed_video_call: 'Chiamata video persa',
    missed_voice_call: 'Chiamata vocale persa',
    video_call_log: 'Chiamata video',
    voice_call_log: 'Chiamata vocale',
    online_status: 'Online',
    language_name: 'Italian',
    // Landing page translations
    hero_badge: 'La migliore piattaforma di viaggio della Mongolia',
    hero_subtitle: 'Trova guide professionali, prenota tour, scopri destinazioni mozzafiato — tutto in un unico posto.',
    stat_guides: 'Guide',
    stat_travelers: 'Viaggiatori',
    stat_destinations: 'Destinazioni',
    stat_languages: 'Lingue',
    get_started: 'Inizia ora',
    services_title: 'Servizi',
    services_desc: 'Soddisfa tutte le tue esigenze di viaggio attraverso la piattaforma VIP Travel.',
    service_find_guide: 'Trova una guida',
    service_find_guide_desc: 'Sfoglia e confronta guide locali e internazionali, visualizza valutazioni e recensioni per trovare la guida perfetta.',
    service_book_tour: 'Prenota un tour',
    service_book_tour_desc: 'Contatta direttamente le guide per prenotare tour. Pagamento facile via QPay, SocialPay o carta.',
    service_interactive_map: 'Mappa interattiva',
    service_interactive_map_desc: 'Alimentata da Mapbox. Vedi guide e fornitori in tempo reale su una mappa interattiva.',
    view_all_services: 'Vedi tutti i servizi',
    all_services_title: 'Tutti i servizi',
    all_services_desc: 'Tutti i servizi della piattaforma VIP Travel',
    service_translator: 'Traduttore',
    service_translator_desc: 'Traduzione integrata che supporta 10 lingue per una comunicazione fluida tra guide e viaggiatori.',
    service_chat_calls: 'Chat e chiamate',
    service_chat_calls_desc: 'Messaggi diretti e videochiamate tramite Cloudflare Calls.',
    service_social_feed: 'Feed social',
    service_social_feed_desc: 'Condividi momenti di viaggio, pubblica foto e video, lascia recensioni, unisciti alla comunità di viaggio.',
    service_provider_services: 'Servizi fornitori',
    service_provider_services_desc: 'Prenota campeggi, spa, trasporti, ristoranti e noleggi in un unico posto.',
    service_guide_verification: 'Verifica guide',
    service_guide_verification_desc: 'Tutte le guide verificate con documenti ufficiali e certificati. Viaggio sicuro e affidabile garantito.',
    service_live_streaming: 'Streaming live',
    service_live_streaming_desc: 'Guarda stream live dalle guide e destinazioni per anteprima della tua avventura.',
    footer_copyright: '© 2026 VIP Travel. Tutti i diritti riservati.',
    footer_terms: 'Termini di servizio'
  }
};

export const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('cj_travel_lang') as Language;
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('cj_travel_lang', lang);
  };

  const t = (key: string) => {
    const translation = translations[language][key as keyof typeof translations['en']];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);